# ASSIGNMENT 4

-----
## NAME : ADESH VIJAY RODIYE 
## PRN : 8005
-----

### 1. Write a Pandas program to read a csv file from a specified source and print the first 5 rows. (Diamonds.csv)

In [127]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [128]:
df = pd.read_csv("diamonds.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

### 2. Write a Pandas program to read a dataset from diamonds DataFrame and modify the default columns values and print the first 6 rows

In [129]:
df.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

In [130]:
df = df.drop(columns=["Unnamed: 0"])

In [131]:
df1 = df.copy()
df1['cut'] = df1['cut'].astype(str).str.upper()
df1['price'] = df1['price'] * 2

In [132]:
df1.head(6)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      IDEAL     E     SI2   61.5   55.0    652  3.95  3.98  2.43
1   0.21    PREMIUM     E     SI1   59.8   61.0    652  3.89  3.84  2.31
2   0.23       GOOD     E     VS1   56.9   65.0    654  4.05  4.07  2.31
3   0.29    PREMIUM     I     VS2   62.4   58.0    668  4.20  4.23  2.63
4   0.31       GOOD     J     SI2   63.3   58.0    670  4.34  4.35  2.75
5   0.24  VERY GOOD     J    VVS2   62.8   57.0    672  3.94  3.96  2.48

### 3. Write a Pandas program to select a series from diamonds DataFrame. Print the content of the series.

In [133]:
Carat_Weight = df["carat"]
Carat_Weight

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

### 4. Write a Pandas program to create a new 'Quality -color' Series (use bracket notation to define the Series name) of the diamonds DataFrame.

In [134]:
df['Quality -color'] = df['cut'] + ', ' + df['color']
df

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality -color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 5. Write a Pandas program to find the number of rows and columns and data type of each column of diamonds Dataframe.

In [135]:
df.shape

(53940, 11)

In [136]:
rows,columns = df.shape
print("Rows : ",rows)
print("Columns : ",columns)

Rows :  53940
Columns :  11

In [137]:
type(df)

pandas.core.frame.DataFrame

In [138]:
df.dtypes

carat             float64
cut                object
color              object
clarity            object
depth             float64
table             float64
price               int64
x                 float64
y                 float64
z                 float64
Quality -color     object
dtype: object

### 6. Write a Pandas program to summarize only 'object' columns of the diamonds Dataframe.

In [139]:
obj_col = df.select_dtypes(include=["object"])
obj_col.head()

       cut color clarity Quality -color
0    Ideal     E     SI2       Ideal, E
1  Premium     E     SI1     Premium, E
2     Good     E     VS1        Good, E
3  Premium     I     VS2     Premium, I
4     Good     J     SI2        Good, J

In [140]:
obj_col.describe()

          cut  color clarity Quality -color
count   53940  53940   53940          53940
unique      5      7       8             35
top     Ideal      G     SI1       Ideal, G
freq    21551  11292   13065           4884

### 7. Write a Pandas program to rename two of the columns of the diamonds Dataframe.

In [141]:
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality -color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"

In [142]:
df.rename(columns={"carat":"Carat_Weight","cut":"Cut_Quality"},inplace=True)
df.head()

,Carat_Weight,Cut_Quality,color,clarity,depth,table,price,x,y,z,Quality -color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"

### 8. Write a Pandas program to rename all the columns of the diamonds Dataframe.

In [143]:
new_col_name = ['Carat', 'Cut', 'Color', 'Clarity', 'Depth_Pct', 'Table_Pct', 'Price', 'Length_X', 'Width_Y', 'Depth_Z',"Quality_Color"]
df.columns = new_col_name
df.head()

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"

### 9. Write a Pandas program to remove the second column of the diamonds Dataframe.

In [144]:
df.drop(columns=["Cut"])

,Carat,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
0,0.23,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 10. Write a Pandas program to remove multiple columns at once of the diamonds Dataframe

In [146]:
df.drop(columns=["Cut","Color","Length_X","Width_Y","Depth_Z"])

       Carat Clarity  Depth_Pct  Table_Pct  Price Quality_Color
0       0.23     SI2       61.5       55.0    326      Ideal, E
1       0.21     SI1       59.8       61.0    326    Premium, E
2       0.23     VS1       56.9       65.0    327       Good, E
3       0.29     VS2       62.4       58.0    334    Premium, I
4       0.31     SI2       63.3       58.0    335       Good, J
...      ...     ...        ...        ...    ...           ...
53935   0.72     SI1       60.8       57.0   2757      Ideal, D
53936   0.72     SI1       63.1       55.0   2757       Good, D
53937   0.70     SI1       62.8       60.0   2757  Very Good, D
53938   0.86     SI2       61.0       58.0   2757    Premium, H
53939   0.75     SI2       62.2       55.0   2757      Ideal, D

[53940 rows x 6 columns]

### 11. Write a Pandas program to remove multiple rows at once (axis=0 refers to rows) from diamonds dataframe.

In [159]:
df.head(10)

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,"Very Good, J"
6,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47,"Very Good, I"
7,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53,"Very Good, H"
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,"Fair, E"
9,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39,"Very Good, H"

In [163]:
df.drop([0,1,2,4,6])

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,"Very Good, J"
7,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53,"Very Good, H"
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,"Fair, E"
9,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39,"Very Good, H"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [164]:
df.drop(df.index[0:10])

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73,"Good, J"
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46,"Ideal, J"
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,"Premium, F"
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71,"Ideal, J"
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,"Premium, E"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [148]:
df["Price"].describe()

count    53940.000000
mean      3932.799722
std       3989.439738
min        326.000000
25%        950.000000
50%       2401.000000
75%       5324.250000
max      18823.000000
Name: Price, dtype: float64

In [156]:
df.drop(df[df["Price"]<950].index)

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
90,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57,"Ideal, E"
91,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52,"Fair, E"
92,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50,"Ideal, G"
93,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56,"Very Good, E"
94,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72,"Very Good, G"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 12. Write a Pandas program to sort the 'cut' Series in ascending order (returns a Series) of diamonds Dataframe

In [166]:
s1 = df["Cut"].sort_values(ascending=True)
s1

3850          Fair
51464         Fair
51466         Fair
10237         Fair
10760         Fair
           ...
7402     Very Good
43101    Very Good
16893    Very Good
16898    Very Good
21164    Very Good
Name: Cut, Length: 53940, dtype: object

### 13. Write a Pandas program to sort the 'price' Series in descending order (returns a Series) of diamonds Dataframe.

In [167]:
s2 = df["Price"].sort_values(ascending=False)
s2

27749    18823
27748    18818
27747    18806
27746    18804
27745    18803
         ...
4          335
3          334
2          327
1          326
0          326
Name: Price, Length: 53940, dtype: int64

### 14. Write a Pandas program to sort the entire diamonds DataFrame by the 'carat' Series in ascending and descending order

In [169]:
df.sort_values("Carat",ascending=True)

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
31593,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,"Premium, E"
31597,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,"Ideal, D"
31596,0.20,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,"Premium, F"
31595,0.20,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30,"Ideal, E"
31594,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28,"Premium, E"
...,...,...,...,...,...,...,...,...,...,...,...
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,"Premium, J"
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,"Premium, I"
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,"Fair, H"
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,"Fair, J"
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,"Fair, J"

In [170]:
df.sort_values("Carat",ascending=False)

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,"Fair, J"
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,"Fair, J"
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,"Fair, H"
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,"Premium, J"
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,"Premium, I"
...,...,...,...,...,...,...,...,...,...,...,...
31592,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,"Premium, E"
31591,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26,"Premium, E"
31601,0.20,Premium,D,VS2,61.7,60.0,367,3.77,3.72,2.31,"Premium, D"
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,"Premium, E"
31596,0.20,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,"Premium, F"

### 15. Write a Pandas program to filter the DataFrame rows to only show carat weight at least 0.3

In [171]:
filt = df["Carat"] >= 0.3
df[filt]

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73,"Good, J"
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71,"Ideal, J"
15,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68,"Premium, E"
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68,"Ideal, I"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 16. Write a Pandas program to convert a python list to pandas series.

In [173]:
list1 = [10,20,30,40,50,60,70,80,90,100]
list1

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [174]:
series = pd.Series(list1)
series

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

### 17. Write a Pandas program to find the details of the diamonds where length>5, width>5 and depth>5.

In [176]:
df.columns

Index(['Carat', 'Cut', 'Color', 'Clarity', 'Depth_Pct', 'Table_Pct', 'Price',
       'Length_X', 'Width_Y', 'Depth_Z', 'Quality_Color'],
      dtype='object')

In [178]:
filt = (df["Length_X"] > 5)  & (df["Width_Y"] > 5) & (df["Width_Y"] > 5)
df[filt]

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
90,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57,"Ideal, E"
91,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52,"Fair, E"
92,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50,"Ideal, G"
93,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56,"Very Good, E"
94,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72,"Very Good, G"
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 18. Write a Pandas program to find the diamonds that are either Premium or Ideal

In [182]:
filt = (df["Cut"] =="Premium") | (df["Cut"] =="Ideal")
df[filt]

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46,"Ideal, J"
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,"Premium, F"
...,...,...,...,...,...,...,...,...,...,...,...
53931,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,"Premium, F"
53934,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,"Premium, D"
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

### 19. Write a Pandas program to find the diamonds that are with a Fair or Good or Premium.

In [183]:
filt = (df["Cut"] == "Fair") | (df["Cut"] =="Premium") | (df["Cut"] =="Good")
df[filt]

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,"Fair, E"
...,...,...,...,...,...,...,...,...,...,...,...
53930,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49,"Premium, E"
53931,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,"Premium, F"
53934,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,"Premium, D"
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"

### 20. Write a Pandas program to display all column labels of diamonds DataFrame

In [184]:
df.columns

Index(['Carat', 'Cut', 'Color', 'Clarity', 'Depth_Pct', 'Table_Pct', 'Price',
       'Length_X', 'Width_Y', 'Depth_Z', 'Quality_Color'],
      dtype='object')

### 21. Write a Pandas program to read only a subset of 3 rows from diamonds DataFrame.

In [185]:
df[0:3]

,Carat,Cut,Color,Clarity,Depth_Pct,Table_Pct,Price,Length_X,Width_Y,Depth_Z,Quality_Color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"

### 22. Write a Pandas program to iterate through diamonds DataFrame.

### 23. Write a Pandas program to drop all non-numeric columns from diamonds DataFrame

In [189]:
df.dtypes

Carat            float64
Cut               object
Color             object
Clarity           object
Depth_Pct        float64
Table_Pct        float64
Price              int64
Length_X         float64
Width_Y          float64
Depth_Z          float64
Quality_Color     object
dtype: object

In [193]:
df.drop(columns=df.select_dtypes(exclude=["number"]).columns)

       Carat  Depth_Pct  Table_Pct  Price  Length_X  Width_Y  Depth_Z
0       0.23       61.5       55.0    326      3.95     3.98     2.43
1       0.21       59.8       61.0    326      3.89     3.84     2.31
2       0.23       56.9       65.0    327      4.05     4.07     2.31
3       0.29       62.4       58.0    334      4.20     4.23     2.63
4       0.31       63.3       58.0    335      4.34     4.35     2.75
...      ...        ...        ...    ...       ...      ...      ...
53935   0.72       60.8       57.0   2757      5.75     5.76     3.50
53936   0.72       63.1       55.0   2757      5.69     5.75     3.61
53937   0.70       62.8       60.0   2757      5.66     5.68     3.56
53938   0.86       61.0       58.0   2757      6.15     6.12     3.74
53939   0.75       62.2       55.0   2757      5.83     5.87     3.64

[53940 rows x 7 columns]

### 24. Write a Pandas program to include only numeric columns in the diamonds DataFrame

In [ ]:
d