In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('tips')

In [4]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
len(df)

244

In [7]:
df.columns.tolist()

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [8]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [9]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [10]:
df.isnull()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [11]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [12]:
df.duplicated().sum()

1

In [13]:
summary = df.groupby('day')['tip'].mean().round(2)
summary

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Temp\ipykernel_17036\1117670439.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = df.groupby('day')['tip'].mean().round(2)

day
Thur    2.77
Fri     2.73
Sat     2.99
Sun     3.26
Name: tip, dtype: float64

In [14]:
summary.to_csv('tips_average_by_day.csv')

In [15]:
# working with clm
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [16]:
df.tip.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [17]:
df.loc[df['total_bill'].idxmax()]

total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

In [18]:
df.loc[df['total_bill'].idxmin()]

total_bill      3.07
tip              1.0
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               1
Name: 67, dtype: object

In [19]:
df.loc[0,'tip']=1.50
df.loc[df['size']>=5,'time'] = 'Dinner'

In [20]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.50  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [21]:
df.loc[df['size']>=5,['size','time']]

     size    time
125     6  Dinner
141     6  Dinner
142     5  Dinner
143     6  Dinner
155     5  Dinner
156     6  Dinner
185     5  Dinner
187     5  Dinner
216     5  Dinner

In [22]:
df['tip_%'] = (100*df['tip']/df['total_bill']).round(2)
df

     total_bill   tip     sex smoker   day    time  size  tip_%
0         16.99  1.50  Female     No   Sun  Dinner     2   8.83
1         10.34  1.66    Male     No   Sun  Dinner     3  16.05
2         21.01  3.50    Male     No   Sun  Dinner     3  16.66
3         23.68  3.31    Male     No   Sun  Dinner     2  13.98
4         24.59  3.61  Female     No   Sun  Dinner     4  14.68
..          ...   ...     ...    ...   ...     ...   ...    ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2   7.36
241       22.67  2.00    Male    Yes   Sat  Dinner     2   8.82
242       17.82  1.75    Male     No   Sat  Dinner     2   9.82
243       18.78  3.00  Female     No  Thur  Dinner     2  15.97

[244 rows x 8 columns]

In [23]:
df['price_per_person'] = (df['total_bill']/df['size'])
df

,total_bill,tip,sex,smoker,day,time,size,tip_%,price_per_person
0,16.99,1.50,Female,No,Sun,Dinner,2,8.83,8.495000
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,3.446667
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,7.003333
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,11.840000
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,6.147500
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,9.676667
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.36,13.590000
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.82,11.335000
242,17.82,1.75,Male,No,Sat,Dinner,2,9.82,8.910000
243,18.78,3.00,Female,No,Thur,Dinner,2,15.97,9.390000

In [24]:
df(['total_bill','tip','size','tip_%','price_per_person']).head()

TypeError: 'DataFrame' object is not callable

In [25]:
df['big_tipper'] = np.where(df['tip_%']>20,'Yes','No')

In [26]:
df

,total_bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper
0,16.99,1.50,Female,No,Sun,Dinner,2,8.83,8.495000,No
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,3.446667,No
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,7.003333,No
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,11.840000,No
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,6.147500,No
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,9.676667,Yes
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.36,13.590000,No
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.82,11.335000,No
242,17.82,1.75,Male,No,Sat,Dinner,2,9.82,8.910000,No
243,18.78,3.00,Female,No,Thur,Dinner,2,15.97,9.390000,No

In [27]:
df['bill_category']=np.select(
    [df['total_bill']<10,df['total_bill']<30],
    ['$','$$'],default='$$$')

In [28]:
df

,total_bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,3.446667,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,7.003333,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,11.840000,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,6.147500,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,9.676667,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.36,13.590000,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.82,11.335000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,15.97,9.390000,No,$$

In [29]:
df[['total_bill','bill_category']]

     total_bill bill_category
0         16.99            $$
1         10.34            $$
2         21.01            $$
3         23.68            $$
4         24.59            $$
..          ...           ...
239       29.03            $$
240       27.18            $$
241       22.67            $$
242       17.82            $$
243       18.78            $$

[244 rows x 2 columns]

In [30]:
df = df.rename(columns={'total_bill':'bill','Payer Name':'payer name'})
df

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,3.446667,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,7.003333,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,11.840000,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,6.147500,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,9.676667,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.36,13.590000,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.82,11.335000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,15.97,9.390000,No,$$

In [31]:
df['size']=df['size'].astype(float)
df

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3.0,16.66,7.003333,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2.0,13.98,11.840000,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4.0,14.68,6.147500,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3.0,20.39,9.676667,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2.0,7.36,13.590000,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2.0,8.82,11.335000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [32]:
df['day']=df['day'].astype('category')
df

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3.0,16.66,7.003333,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2.0,13.98,11.840000,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4.0,14.68,6.147500,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3.0,20.39,9.676667,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2.0,7.36,13.590000,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2.0,8.82,11.335000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [33]:
df.dtypes

bill                 float64
tip                  float64
sex                 category
smoker              category
day                 category
time                category
size                 float64
tip_%                float64
price_per_person     float64
big_tipper            object
bill_category         object
dtype: object

In [34]:
raw = pd.Series(['10','20','abc',None,'7.5'])
raw

0      10
1      20
2     abc
3    None
4     7.5
dtype: object

In [35]:
print(pd.to_numeric(raw, errors='coerce'))

0    10.0
1    20.0
2     NaN
3     NaN
4     7.5
dtype: float64

In [36]:
raw = pd.Series(['10','20','abc',None,'7.5'])
pd.to_numeric(raw,errors='coerce').fillna(0).astype(int)

0    10
1    20
2     0
3     0
4     7
dtype: int32

In [38]:
df['bill']>30

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: bill, Length: 244, dtype: bool

In [39]:
df[df['bill']>30]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
11,35.26,5.00,Female,No,Sun,Dinner,4.0,14.18,8.815000,No,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4.0,19.23,9.855000,No,$$$
39,31.27,5.00,Male,No,Sat,Dinner,3.0,15.99,10.423333,No,$$$
44,30.40,5.60,Male,No,Sun,Dinner,4.0,18.42,7.600000,No,$$$
47,32.40,6.00,Male,No,Sun,Dinner,4.0,18.52,8.100000,No,$$$
52,34.81,5.20,Female,No,Sun,Dinner,4.0,14.94,8.702500,No,$$$
56,38.01,3.00,Male,Yes,Sat,Dinner,4.0,7.89,9.502500,No,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4.0,13.94,12.067500,No,$$$
83,32.68,5.00,Male,Yes,Thur,Lunch,2.0,15.30,16.340000,No,$$$
85,34.83,5.17,Female,No,Thur,Lunch,4.0,14.84,8.707500,No,$$$
95,40.17,4.73,Male,Yes,Fri,Dinner,4.0,11.77,10.042500,No,$$$
102,44.30,2.50,Female,Yes,Sat,Dinner,3.0,5.64,14.766667,No,$$$
112,38.07,4.00,Male,No,Sun,Dinner,3.0,10.51,12.690000,No,$$$
141,34.30,6.70,Male,No,Thur,Dinner,6.0,19.53,5.716667,No,$$$
142,41.19,5.00,Male,No,Thur,Dinner,5.0,12.14,8.238000,No,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6.0,10.38,8.028333,No,$$$
167,31.71,4.50,Male,No,Sun,Dinner,4.0,14.19,7.927500,No,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3.0,19.68,16.936667,No,$$$
173,31.85,3.18,Male,Yes,Sun,Dinner,2.0,9.98,15.925000,No,$$$
175,32.90,3.11,Male,Yes,Sun,Dinner,2.0,9.45,16.450000,No,$$$
179,34.63,3.55,Male,Yes,Sun,Dinner,2.0,10.25,17.315000,No,$$$
180,34.65,3.68,Male,Yes,Sun,Dinner,4.0,10.62,8.662500,No,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3.0,7.72,15.116667,No,$$$
184,40.55,3.00,Male,Yes,Sun,Dinner,2.0,7.40,20.275000,No,$$$
187,30.46,2.00,Male,Yes,Sun,Dinner,5.0,6.57,6.092000,No,$$$
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,11.60,10.777500,No,$$$
207,38.73,3.00,Male,Yes,Sat,Dinner,4.0,7.75,9.682500,No,$$$
210,30.06,2.00,Male,Yes,Sat,Dinner,3.0,6.65,10.020000,No,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4.0,18.62,12.082500,No,$$$
219,30.14,3.09,Female,Yes,Sat,Dinner,4.0,10.25,7.535000,No,$$$
237,32.83,1.17,Male,Yes,Sat,Dinner,2.0,3.56,16.415000,No,$$$
238,35.83,4.67,Female,No,Sat,Dinner,3.0,13.03,11.943333,No,$$$

In [45]:
df[(df['bill']>30) & ~(df['sex']=='Male')]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
11,35.26,5.00,Female,No,Sun,Dinner,4.0,14.18,8.815000,No,$$$
52,34.81,5.20,Female,No,Sun,Dinner,4.0,14.94,8.702500,No,$$$
85,34.83,5.17,Female,No,Thur,Lunch,4.0,14.84,8.707500,No,$$$
102,44.30,2.50,Female,Yes,Sat,Dinner,3.0,5.64,14.766667,No,$$$
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,11.60,10.777500,No,$$$
219,30.14,3.09,Female,Yes,Sat,Dinner,4.0,10.25,7.535000,No,$$$
238,35.83,4.67,Female,No,Sat,Dinner,3.0,13.03,11.943333,No,$$$

In [46]:
df[(df['bill']>30) & (df['sex']=='Male')]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
23,39.42,7.58,Male,No,Sat,Dinner,4.0,19.23,9.855000,No,$$$
39,31.27,5.00,Male,No,Sat,Dinner,3.0,15.99,10.423333,No,$$$
44,30.40,5.60,Male,No,Sun,Dinner,4.0,18.42,7.600000,No,$$$
47,32.40,6.00,Male,No,Sun,Dinner,4.0,18.52,8.100000,No,$$$
56,38.01,3.00,Male,Yes,Sat,Dinner,4.0,7.89,9.502500,No,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4.0,13.94,12.067500,No,$$$
83,32.68,5.00,Male,Yes,Thur,Lunch,2.0,15.30,16.340000,No,$$$
95,40.17,4.73,Male,Yes,Fri,Dinner,4.0,11.77,10.042500,No,$$$
112,38.07,4.00,Male,No,Sun,Dinner,3.0,10.51,12.690000,No,$$$
141,34.30,6.70,Male,No,Thur,Dinner,6.0,19.53,5.716667,No,$$$
142,41.19,5.00,Male,No,Thur,Dinner,5.0,12.14,8.238000,No,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6.0,10.38,8.028333,No,$$$
167,31.71,4.50,Male,No,Sun,Dinner,4.0,14.19,7.927500,No,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3.0,19.68,16.936667,No,$$$
173,31.85,3.18,Male,Yes,Sun,Dinner,2.0,9.98,15.925000,No,$$$
175,32.90,3.11,Male,Yes,Sun,Dinner,2.0,9.45,16.450000,No,$$$
179,34.63,3.55,Male,Yes,Sun,Dinner,2.0,10.25,17.315000,No,$$$
180,34.65,3.68,Male,Yes,Sun,Dinner,4.0,10.62,8.662500,No,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3.0,7.72,15.116667,No,$$$
184,40.55,3.00,Male,Yes,Sun,Dinner,2.0,7.40,20.275000,No,$$$
187,30.46,2.00,Male,Yes,Sun,Dinner,5.0,6.57,6.092000,No,$$$
207,38.73,3.00,Male,Yes,Sat,Dinner,4.0,7.75,9.682500,No,$$$
210,30.06,2.00,Male,Yes,Sat,Dinner,3.0,6.65,10.020000,No,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4.0,18.62,12.082500,No,$$$
237,32.83,1.17,Male,Yes,Sat,Dinner,2.0,3.56,16.415000,No,$$$

In [47]:
#Membership and ranges
df[df['day'].isin(['Sat','Sun'])].shape

(163, 11)

In [49]:
df[df['bill'].between(10,20)]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,13.03,7.520000,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,21.85,7.390000,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,16.65,5.135000,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,19.32,7.765000,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,12.41,5.035000,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,7.94,6.300000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [50]:
df[df['bill'].between(10,20, inclusive='left')]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,13.03,7.520000,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,21.85,7.390000,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,16.65,5.135000,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,19.32,7.765000,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,12.41,5.035000,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,7.94,6.300000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [55]:
df[df['bill'].between(10,20, inclusive='right')]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,13.03,7.520000,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,21.85,7.390000,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,16.65,5.135000,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,19.32,7.765000,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,12.41,5.035000,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,7.94,6.300000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [53]:
df[df['bill'].between(10,20, inclusive='neither')]

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.83,8.495000,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,16.05,3.446667,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,13.03,7.520000,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,21.85,7.390000,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,16.65,5.135000,No,$$
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,19.32,7.765000,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,12.41,5.035000,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,7.94,6.300000,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,9.82,8.910000,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,15.97,9.390000,No,$$

In [ ]:
# Text Colm
df[df['Payer Name'].str.contains('Smith',case=False)]

In [ ]:
df[df['Payment ID'].str.startswith('Sun')].shape

In [61]:
filt1 = df[(df['sex']=='Female')&(df['tip']>=4)]
filt1

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
11,35.26,5.00,Female,No,Sun,Dinner,4.0,14.18,8.815000,No,$$$
52,34.81,5.20,Female,No,Sun,Dinner,4.0,14.94,8.702500,No,$$$
73,25.28,5.00,Female,Yes,Sat,Dinner,2.0,19.78,12.640000,No,$$
85,34.83,5.17,Female,No,Thur,Lunch,4.0,14.84,8.707500,No,$$$
93,16.32,4.30,Female,Yes,Fri,Dinner,2.0,26.35,8.160000,Yes,$$
104,20.92,4.08,Female,No,Sat,Dinner,2.0,19.50,10.460000,No,$$
109,14.31,4.00,Female,Yes,Sat,Dinner,2.0,27.95,7.155000,Yes,$$
114,25.71,4.00,Female,No,Sun,Dinner,3.0,15.56,8.570000,No,$$
125,29.80,4.20,Female,No,Thur,Dinner,6.0,14.09,4.966667,No,$$
143,27.05,5.00,Female,No,Thur,Dinner,6.0,18.48,4.508333,No,$$
155,29.85,5.14,Female,No,Sun,Dinner,5.0,17.22,5.970000,No,$$
178,9.60,4.00,Female,Yes,Sun,Dinner,2.0,41.67,4.800000,Yes,$
191,19.81,4.19,Female,Yes,Thur,Lunch,2.0,21.15,9.905000,Yes,$$
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,11.60,10.777500,No,$$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3.0,23.07,9.390000,Yes,$$
238,35.83,4.67,Female,No,Sat,Dinner,3.0,13.03,11.943333,No,$$$

In [66]:
min_tip = 4
filt2 = df.query("sex=='Female' and tip >= @min_tip")
filt2

,bill,tip,sex,smoker,day,time,size,tip_%,price_per_person,big_tipper,bill_category
11,35.26,5.00,Female,No,Sun,Dinner,4.0,14.18,8.815000,No,$$$
52,34.81,5.20,Female,No,Sun,Dinner,4.0,14.94,8.702500,No,$$$
73,25.28,5.00,Female,Yes,Sat,Dinner,2.0,19.78,12.640000,No,$$
85,34.83,5.17,Female,No,Thur,Lunch,4.0,14.84,8.707500,No,$$$
93,16.32,4.30,Female,Yes,Fri,Dinner,2.0,26.35,8.160000,Yes,$$
104,20.92,4.08,Female,No,Sat,Dinner,2.0,19.50,10.460000,No,$$
109,14.31,4.00,Female,Yes,Sat,Dinner,2.0,27.95,7.155000,Yes,$$
114,25.71,4.00,Female,No,Sun,Dinner,3.0,15.56,8.570000,No,$$
125,29.80,4.20,Female,No,Thur,Dinner,6.0,14.09,4.966667,No,$$
143,27.05,5.00,Female,No,Thur,Dinner,6.0,18.48,4.508333,No,$$
155,29.85,5.14,Female,No,Sun,Dinner,5.0,17.22,5.970000,No,$$
178,9.60,4.00,Female,Yes,Sun,Dinner,2.0,41.67,4.800000,Yes,$
191,19.81,4.19,Female,Yes,Thur,Lunch,2.0,21.15,9.905000,Yes,$$
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,11.60,10.777500,No,$$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3.0,23.07,9.390000,Yes,$$
238,35.83,4.67,Female,No,Sat,Dinner,3.0,13.03,11.943333,No,$$$

In [ ]:
filt3 = df.loc[df['sex']=='Female')&(df['tip']

In [ ]:
#difff concat $ merge