In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)
scores = np.random.randint(0,101,(4,3))

In [3]:
scores

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [7]:
players = ['Virat','Rohit','MS Dhoni','KL Rahul']
players

['Virat', 'Rohit', 'MS Dhoni', 'KL Rahul']

In [8]:
matches = ['Match 1','Match 2','Match 3']
matches

['Match 1', 'Match 2', 'Match 3']

In [12]:
df = pd.DataFrame(data=scores)
df

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [13]:
df = pd.DataFrame(data=scores,index=players,columns=matches)
df

          Match 1  Match 2  Match 3
Virat          95       11       81
Rohit          70       63       87
MS Dhoni       75        9       77
KL Rahul       40        4       63

In [14]:
# DF from Dict
df = pd.DataFrame({
    'Compony':['TCS','Infosys','Wipro'],
    'Sales':['100','200','300'],
    'Profit':['20','50','70']})
df

   Compony Sales Profit
0      TCS   100     20
1  Infosys   200     50
2    Wipro   300     70

In [15]:
df.shape

(3, 3)

In [16]:
df.size

9

In [17]:
df.columns

Index(['Compony', 'Sales', 'Profit'], dtype='object')

In [20]:
df.dtypes

Compony    object
Sales      object
Profit     object
dtype: object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Compony  3 non-null      object
 1   Sales    3 non-null      object
 2   Profit   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [22]:
df.head()

   Compony Sales Profit
0      TCS   100     20
1  Infosys   200     50
2    Wipro   300     70

In [23]:
df = pd.DataFrame(data=scores,index=players,columns=matches)
df
type(df["Match 1"])

pandas.core.series.Series