### 1) Given a list of five integers, find the minimum and maximum sum using exactly three of the five integers. 5 Marks List = [10,12,1,3,7]

In [5]:
marks = [10,12,1,3,7]

In [6]:
sorted_marks = sorted(marks)

In [9]:
sorted_marks

[1, 3, 7, 10, 12]

In [8]:
sum(sorted_marks[:3])

11

In [11]:
sum(sorted_marks[-3:])

29

-----------

In [20]:
marks = [10,12,1,3,7]
n = len(marks)

In [21]:
for i in range(n):
    for j in range(0,n-1-i):
        if marks[j] > marks[j+1]:
            marks[j],marks[j+1]=marks[j+1],marks[j]

In [22]:
marks

[1, 3, 7, 10, 12]

In [23]:
min = sum(marks[:3])
max = sum(marks[-3:])
print(min)
print(max)

11
29

2) Given a list containing scores of a batsman in a tournament,determine the
number of times he breaks his record for highest and lowest score in the
tournament . 5 Marks
Sample input :- list1 = [ 10, 5 , 20 , 20 , 4 , 5 , 2 , 25 , 1]
output : [2,4 ]
he breaks his record for highest run in 3rd & 8th game
he breaks his record for lowest run in 2nd ,5th, 7th & 9th game

In [30]:
n = int(input("Enter number of games:"))

scores = []

for i in range(n):
    score = int(input(f"Enter score of game {i+1} : "))
    scores.append(score)

scores

Enter number of games: 10
Enter score of game 1 :  50
Enter score of game 2 :  45
Enter score of game 3 :  60
Enter score of game 4 :  56
Enter score of game 5 :  75
Enter score of game 6 :  88
Enter score of game 7 :  90
Enter score of game 8 :  20
Enter score of game 9 :  66
Enter score of game 10 :  100

[50, 45, 60, 56, 75, 88, 90, 20, 66, 100]

In [31]:
min_score = scores[0]
max_score = scores[0]

highest_breaks = 0
lowest_breaks = 0

for score in scores[1:]:
    if score > max_score:
        max_score = score
        highest_breaks += 1
    elif score < min_score:
        min_score = score
        lowest_breaks += 1

output = [highest_breaks,lowest_breaks]
output

[5, 2]

3) A SPECIAL STRING has the following properties: 
● It is a concatenation of one or more words consisting of English letters.
● All letters in the first word are lowercase.
● For each of the subsequent words, the first letter is uppercase and the rest of the
letters are lowercase.
Given a special string, find the number of words in it.
Sample input : pgdaiAtCdacPatna
Output : 4

In [32]:
string = "pgdaiAtCdacPatna"
count = 1

for char in string:
    if char.isupper():
        count +=1
count

4

4) From the given CSV file, perform the following operations: 10 Marks
○ Read the data in a dataframe.
○ Find the row having the maximum temperature.
○ Find the mean,max,min,standard deviation,25 percentile,50 percentile,75
percentile for Temperature column.
○ Replace the missing values in ‘WindSpeedMPH’ column with the mean
value.

In [35]:
import numpy as np
import pandas as pd
import seaborn as sns

In [46]:
df = pd.read_csv("temperature.csv")
df

,record_id,month,day,year,AverageTemperatureFahr,AverageTemperatureUncertaintyFahr,City,country_id,Country,Latitude,Longitude
0,474376,1,1,1853,NaN,NaN,Auckland,NEW,New Zealand,36.17S,175.03E
1,474377,2,1,1853,NaN,NaN,Auckland,NEW,New Zealand,36.17S,175.03E
2,474378,3,1,1853,NaN,NaN,Auckland,NEW,New Zealand,36.17S,175.03E
3,474379,4,1,1853,NaN,NaN,Auckland,NEW,New Zealand,36.17S,175.03E
4,474380,5,1,1853,NaN,NaN,Auckland,NEW,New Zealand,36.17S,175.03E
...,...,...,...,...,...,...,...,...,...,...,...
48465,8258726,5,1,2013,55.0544,32.4896,Wroclaw,POL,Poland,50.63N,16.48E
48466,8258727,6,1,2013,61.1672,32.3330,Wroclaw,POL,Poland,50.63N,16.48E
48467,8258728,7,1,2013,66.7706,32.5706,Wroclaw,POL,Poland,50.63N,16.48E
48468,8258729,8,1,2013,64.5656,32.4842,Wroclaw,POL,Poland,50.63N,16.48E
48469,8258730,9,1,2013,NaN,NaN,Wroclaw,POL,Poland,50.63N,16.48E

In [47]:
df.isnull().sum()

record_id                              0
month                                  0
day                                    0
year                                   0
AverageTemperatureFahr               929
AverageTemperatureUncertaintyFahr    929
City                                 484
country_id                           484
Country                              484
Latitude                               0
Longitude                              0
dtype: int64

In [48]:
df = df.dropna()

In [49]:
df.isnull().sum()

record_id                            0
month                                0
day                                  0
year                                 0
AverageTemperatureFahr               0
AverageTemperatureUncertaintyFahr    0
City                                 0
country_id                           0
Country                              0
Latitude                             0
Longitude                            0
dtype: int64

In [50]:
df

,record_id,month,day,year,AverageTemperatureFahr,AverageTemperatureUncertaintyFahr,City,country_id,Country,Latitude,Longitude
5,474381,6,1,1853,51.9062,36.9572,Auckland,NEW,New Zealand,36.17S,175.03E
6,474382,7,1,1853,52.3886,34.5488,Auckland,NEW,New Zealand,36.17S,175.03E
7,474383,8,1,1853,52.8530,33.5498,Auckland,NEW,New Zealand,36.17S,175.03E
8,474384,9,1,1853,52.5776,33.6380,Auckland,NEW,New Zealand,36.17S,175.03E
9,474385,10,1,1853,54.8726,33.9836,Auckland,NEW,New Zealand,36.17S,175.03E
...,...,...,...,...,...,...,...,...,...,...,...
48464,8258725,4,1,2013,46.2902,32.2808,Wroclaw,POL,Poland,50.63N,16.48E
48465,8258726,5,1,2013,55.0544,32.4896,Wroclaw,POL,Poland,50.63N,16.48E
48466,8258727,6,1,2013,61.1672,32.3330,Wroclaw,POL,Poland,50.63N,16.48E
48467,8258728,7,1,2013,66.7706,32.5706,Wroclaw,POL,Poland,50.63N,16.48E
48468,8258729,8,1,2013,64.5656,32.4842,Wroclaw,POL,Poland,50.63N,16.48E

In [52]:
df[df["AverageTemperatureFahr"]==df["AverageTemperatureFahr"].max()]

,record_id,month,day,year,AverageTemperatureFahr,AverageTemperatureUncertaintyFahr,City,country_id,Country,Latitude,Longitude
38715,7716910,8,1,2010,84.6554,32.324,Tottori,JAP,Japan,34.56N,134.27E

In [55]:
# Find the mean,max,min,standard deviation,25 percentile,50 percentile,75
# percentile for Temperature column.
df["AverageTemperatureFahr"].mean()

51.74544406815671

In [56]:
df["AverageTemperatureFahr"].max()

84.6554

In [57]:
df["AverageTemperatureFahr"].min()

2.85619999999999

In [58]:
df["AverageTemperatureFahr"].std()

15.06802241864285

In [59]:
df["AverageTemperatureFahr"].quantile(0.25)

40.14995

In [60]:
df["AverageTemperatureFahr"].quantile(0.50)

54.5756

In [61]:
df["AverageTemperatureFahr"].quantile(0.75)

63.7088

5) Two numbers are friends if they leave the same remainder  when divided by 5.
Strength of a number is defined as the total number of friends it has.
Given a list of positive integers, find the total strength of the list.\
Sample input : list1 = [6 ,11 ,16 ,7 ,12]
output = 8
Explanation : 6,11 & 16 are friends because they leave 1 as remainder when
divided by 5. Hence their strength = 2
similarly, 7 & 12 are friends with strength = 1
so total strength = 2*3 + 1*2 = 8

In [63]:
n = int(input("Enter size of list:"))

list1 = []

for i in range(n):
    l = int(input(f"Enter number {i+1} : "))
    list1.append(l)

list1

Enter size of list: 10
Enter number 1 :  6
Enter number 2 :  11
Enter number 3 :  12
Enter number 4 :  7
Enter number 5 :  8
Enter number 6 :  22
Enter number 7 :  51
Enter number 8 :  23
Enter number 9 :  33
Enter number 10 :  47

[6, 11, 12, 7, 8, 22, 51, 23, 33, 47]

[1, 1, 2, 2, 3, 2, 1, 3, 3, 2]

In [72]:
from collections import Counter
reminder = [x % 5 for x in list1]
print("Reminders",reminder)
reminders_count = Counter(reminder)
print("reminders_count",reminders_count)

Reminders [1, 1, 2, 2, 3, 2, 1, 3, 3, 2]
reminders_count Counter({2: 4, 1: 3, 3: 3})

In [74]:
total_strength = sum(c*(c-1) for c in reminders_count.values())
total_strength

24

6) Write a python function to print the even factors of a given number.

In [81]:
def evenFactors(n):
    print("Even Factors of n are : ")
    for i in range(1,n+1):
        if( n%i==0 and i%2==0):
            print(i," ")
evenFactors(60)

Even Factors of n are :
2
4
6
10
12
20
30
60