# Assignment 1

------
## Name : Adesh Vijay Rodiye
## PRN : 8005
------

In [24]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Ridge ,LinearRegression, Lasso, ElasticNet
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import root_mean_squared_error, r2_score

In [25]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [26]:
x,y  = df.drop("charges", axis=1) , df["charges"]

In [27]:
ohc = OneHotEncoder(sparse_output=False, handle_unknown="ignore",drop="first").set_output(transform="pandas")
ct = make_column_transformer((ohc,make_column_selector(dtype_include=object)),("passthrough", make_column_selector(dtype_include=['int64','float64'])),verbose_feature_names_out=False)
ct = ct.set_output(transform="pandas")

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=26,test_size=0.3)

In [29]:
x_ohe_train = ct.fit_transform(x_train)
x_ohe_test = ct.transform(x_test)

## Linear Regression

In [38]:
lr = LinearRegression()
lr.fit(x_ohe_train,y_train)
y_pred = lr.predict(x_ohe_test)
r2_score_lr = r2_score(y_test,y_pred)
r2_score_lr

0.7625873682287878

## Ridge Regression

In [39]:
alphas = np.linspace(0.001,10,20)
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(x_ohe_train,y_train)
    y_pred = ridge.predict(x_ohe_test)
    r2 = r2_score(y_test,y_pred)
    scores.append([a,r2])

df_r2_scores = pd.DataFrame(scores,columns=['alpha','r2 score'])
df_r2_scores.nlargest(1,'r2 score')

   alpha  r2 score
0  0.001  0.762587

In [42]:
r2_score_rd = df_r2_scores['r2 score'].max()
r2_score_rd

0.7625872046054412

## Lasso Regression

In [43]:
alphas = np.linspace(0.001,10,20)
scores = []
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(x_ohe_train,y_train)
    y_pred = lasso.predict(x_ohe_test)
    r2 = r2_score(y_test,y_pred)
    scores.append([a,r2])

df_r2_scores = pd.DataFrame(scores,columns=['alpha','r2 score'])
df_r2_scores.nlargest(1,'r2 score')

   alpha  r2 score
0  0.001  0.762587

In [44]:
r2_score_la = df_r2_scores['r2 score'].max()
r2_score_la

0.7625873640702021

## Elastic Net Regression

In [45]:
alphas = np.linspace(0.001,10,20)
ratios = np.linspace(0.001,1,20)
scores = []
for a in alphas :
    for r in ratios:
        e1 = ElasticNet(alpha=a,l1_ratio=r)
        e1.fit(x_ohe_train,y_train)
        y_pred = e1.predict(x_ohe_test)
        scores.append([a,r,r2_score(y_test,y_pred)])
df_r2_scores = pd.DataFrame(scores,columns=['alpha',"l1",'r2 score'])
df_r2_scores.nlargest(1,'r2 score')

    alpha   l1  r2 score
19  0.001  1.0  0.762587

In [46]:
r2_score_en = df_r2_scores['r2 score'].max()
r2_score_en

0.7625873640702021

In [48]:
models_performance = pd.DataFrame({"Model": ["Linear Regression","Ridge Regression","Lasso Regression","Elastic Net"],
                                   "R2 Score": [r2_score_lr, r2_score_rd, r2_score_la, r2_score_en]})

In [49]:
models_performance

               Model  R2 Score
0  Linear Regression  0.762587
1   Ridge Regression  0.762587
2   Lasso Regression  0.762587
3        Elastic Net  0.762587

In [62]:
print("\nR2 Score for all the models are approximately same.")
print(f"\nBest Model by R2 Score is {models_performance.loc[0, "Model"]} with r2_score = {models_performance.loc[0, "R2 Score"]}")

R2 Score for all the models are approximately same.

Best Model by R2 Score is Linear Regression with r2_score = 0.7625873682287878