# Association Rule

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
df = pd.read_csv("../Datasets/Faceplate.csv",index_col=0)
df

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0
6              0      1     1       0      0       0
7              1      0     1       0      0       0
8              1      1     1       0      1       0
9              1      1     1       0      0       0
10             0      0     0       0      0       1

In [3]:
df = df.astype(bool)
df

               Red  White   Blue  Orange  Green  Yellow
Transaction
1             True   True  False   False   True   False
2            False   True  False    True  False   False
3            False   True   True   False  False   False
4             True   True  False    True  False   False
5             True  False   True   False  False   False
6            False   True   True   False  False   False
7             True  False   True   False  False   False
8             True   True   True   False   True   False
9             True   True   True   False  False   False
10           False  False  False   False  False    True

In [10]:
itemsets = apriori(df, min_support= 0.2, use_colnames=True)
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (Red, White)
6       0.4          (Red, Blue)
7       0.2         (Red, Green)
8       0.4        (Blue, White)
9       0.2      (Orange, White)
10      0.2       (Green, White)
11      0.2   (Red, Blue, White)
12      0.2  (Red, Green, White)

In [11]:
rules = association_rules(itemsets, metric="confidence", min_threshold=0.6)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Red),(White),0.6,0.7,0.4,0.666667,0.952381,1.0,-0.02,0.9,-0.111111,0.444444,-0.111111,0.619048
1,(Red),(Blue),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
2,(Blue),(Red),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
3,(Green),(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500000,0.333333,1.000000,0.666667
4,(Blue),(White),0.6,0.7,0.4,0.666667,0.952381,1.0,-0.02,0.9,-0.111111,0.444444,-0.111111,0.619048
5,(Orange),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
6,(Green),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
7,"(Red, Green)",(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
8,"(Green, White)",(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500000,0.333333,1.000000,0.666667
9,(Green),"(Red, White)",0.2,0.4,0.2,1.000000,2.500000,1.0,0.12,inf,0.750000,0.500000,1.000000,0.750000

In [12]:
rules = association_rules(itemsets, metric="confidence", min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['confidence','lift','support'],ascending=False)

       antecedents   consequents  support  confidence      lift
15         (Green)  (Red, White)      0.2    1.000000  2.500000
4          (Green)         (Red)      0.2    1.000000  1.666667
14  (Green, White)         (Red)      0.2    1.000000  1.666667
7         (Orange)       (White)      0.2    1.000000  1.428571
8          (Green)       (White)      0.2    1.000000  1.428571
12    (Red, Green)       (White)      0.2    1.000000  1.428571
2            (Red)        (Blue)      0.4    0.666667  1.111111
3           (Blue)         (Red)      0.4    0.666667  1.111111
0            (Red)       (White)      0.4    0.666667  0.952381
5           (Blue)       (White)      0.4    0.666667  0.952381
1          (White)         (Red)      0.4    0.571429  0.952381
6          (White)        (Blue)      0.4    0.571429  0.952381
13    (Red, White)       (Green)      0.2    0.500000  2.500000
10    (Red, White)        (Blue)      0.2    0.500000  0.833333
11   (Blue, White)         (Red)      0.2    0.500000  0.833333
9      (Red, Blue)       (White)      0.2    0.500000  0.714286

In [13]:
rules = association_rules(itemsets, metric="confidence", min_threshold=0.6)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['confidence','lift','support'],ascending=False)

      antecedents   consequents  support  confidence      lift
9         (Green)  (Red, White)      0.2    1.000000  2.500000
3         (Green)         (Red)      0.2    1.000000  1.666667
8  (Green, White)         (Red)      0.2    1.000000  1.666667
5        (Orange)       (White)      0.2    1.000000  1.428571
6         (Green)       (White)      0.2    1.000000  1.428571
7    (Red, Green)       (White)      0.2    1.000000  1.428571
1           (Red)        (Blue)      0.4    0.666667  1.111111
2          (Blue)         (Red)      0.4    0.666667  1.111111
0           (Red)       (White)      0.4    0.666667  0.952381
4          (Blue)       (White)      0.4    0.666667  0.952381

In [14]:
rel_rules = rules[rules["lift"]>1]
rel_rules.sort_values(by=['confidence','lift','support'],ascending=False)

      antecedents   consequents  support  confidence      lift
9         (Green)  (Red, White)      0.2    1.000000  2.500000
3         (Green)         (Red)      0.2    1.000000  1.666667
8  (Green, White)         (Red)      0.2    1.000000  1.666667
5        (Orange)       (White)      0.2    1.000000  1.428571
6         (Green)       (White)      0.2    1.000000  1.428571
7    (Red, Green)       (White)      0.2    1.000000  1.428571
1           (Red)        (Blue)      0.4    0.666667  1.111111
2          (Blue)         (Red)      0.4    0.666667  1.111111