In [12]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules
from ipywidgets import interact
import ipywidgets as widgets
from IPython.display import display

In [13]:
groceries = []
with open("../Datasets/DataSetA.csv") as f:groceries = f.read()
groceries = groceries.split("\n")
groceries_list = []
for i in groceries:
    groceries_list.append(i.split(','))

In [14]:
groceries_list[:10]

[['Lassi', 'Coffee Powder', 'Butter', 'Yougurt', 'Ghee', 'Cheese', ''],
 ['Ghee', 'Coffee Powder', ''],
 ['Lassi', 'Tea Powder', 'Butter', 'Cheese', ''],
 ['Cheese', 'Tea Powder', 'Panner', 'Coffee Powder', 'Butter', 'Bread', ''],
 ['Cheese', 'Yougurt', 'Coffee Powder', 'Sugar', 'Butter', 'Sweet', ''],
 ['Sugar', 'Tea Powder', 'Ghee', 'Sweet', 'Panner', 'Milk', ''],
 ['Sweet', 'Coffee Powder', ''],
 ['Butter', 'Ghee', 'Panner', ''],
 ['Sweet', 'Tea Powder', 'Butter', 'Yougurt', 'Sugar', 'Cheese', ''],
 ['Panner', 'Ghee', '']]

In [20]:
te = TransactionEncoder().set_output(transform="pandas")
te_df = te.fit(groceries_list).transform(groceries_list)
te_df

,,Bread,Butter,Cheese,Coffee Powder,Ghee,Lassi,Milk,Panner,Sugar,Sweet,Tea Powder,Yougurt
0,True,False,True,True,True,True,True,False,False,False,False,False,True
1,True,False,False,False,True,True,False,False,False,False,False,False,False
2,True,False,True,True,False,False,True,False,False,False,False,True,False
3,True,True,True,True,True,False,False,False,True,False,False,True,False
4,True,False,True,True,True,False,False,False,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12522,True,True,False,True,True,False,False,False,False,True,False,False,False
12523,True,True,False,True,False,False,False,True,False,False,False,False,True
12524,True,True,False,True,False,True,False,False,False,True,False,False,True
12525,True,True,False,False,False,False,False,False,True,False,False,False,True
12526,True,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
te_df = te_df.iloc[:,1:]
te_df

,Bread,Butter,Cheese,Coffee Powder,Ghee,Lassi,Milk,Panner,Sugar,Sweet,Tea Powder,Yougurt
0,False,True,True,True,True,True,False,False,False,False,False,True
1,False,False,False,True,True,False,False,False,False,False,False,False
2,False,True,True,False,False,True,False,False,False,False,True,False
3,True,True,True,True,False,False,False,True,False,False,True,False
4,False,True,True,True,False,False,False,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
12522,True,False,True,True,False,False,False,False,True,False,False,False
12523,True,False,True,False,False,False,True,False,False,False,False,True
12524,True,False,True,False,True,False,False,False,True,False,False,True
12525,True,False,False,False,False,False,False,True,False,False,False,True
12526,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
def gen_rules (min_support, min_confidence):
    itemsets = apriori(te_df, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets, metric='confidence', min_threshold=min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    rel_rules = rules[rules["lift"]>1]
    return rel_rules.sort_values(by=['confidence','lift','support'],ascending=False)

In [23]:
interact(
    gen_rules, 
    min_support = widgets.FloatSlider(value=0.01, min=0, max=1, step=0.01, description='Min Support:'), 
    min_confidence = widgets.FloatSlider(value=0.01, min=0, max=1, step=0.01, description='Min Confidence:')
)

interactive(children=(FloatSlider(value=0.01, description='Min Support:', max=1.0, step=0.01), FloatSlider(val…

In [24]:
gen_rules (0.6,0.7)

ValueError: The input DataFrame `df` containing the frequent itemsets is empty.