In [ ]:
# KNN
-

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [3]:
milk = pd.read_csv("../Datasets/milk.csv",index_col=0)
milk

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [9]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(milk) # cal mean and sd for all columns
print("Column means : ",scaler.mean_)
print("Column SD : ", scaler.scale_)

Column means :  [78.184   6.212  10.308   4.132   0.8632]
Column SD :  [12.55893881  3.57875062 10.30549058  1.79481921  0.49462487]

In [10]:
milk.describe()

           water    protein        fat   lactose        ash
count  25.000000  25.000000  25.000000  25.00000  25.000000
mean   78.184000   6.212000  10.308000   4.13200   0.863200
std    12.817913   3.652547  10.517997   1.83183   0.504824
min    44.900000   0.600000   1.000000   0.00000   0.100000
25%    71.300000   3.000000   3.400000   2.70000   0.530000
50%    82.000000   5.900000   6.300000   4.70000   0.800000
75%    87.700000   9.700000  13.100000   5.60000   1.100000
max    90.400000  12.300000  42.000000   6.90000   2.300000

In [12]:
milk_scaled = scaler.transform(milk)

In [14]:
milk_scaled.head()

              water   protein       fat   lactose       ash
Animal
HORSE      0.948806 -1.009291 -0.903208  1.542217 -1.037554
ORANGUTAN  0.821407 -1.344603 -0.660619  1.040773 -1.259945
MONKEY     0.813445 -1.121062 -0.738247  1.263637 -1.381249
DONKEY     0.964731 -1.260775 -0.864394  1.152205 -0.936467
HIPPO      0.972694 -1.568145 -0.563583  0.149319 -1.542988

In [18]:
milk_scaled.reset_index().head()

      Animal     water   protein       fat   lactose       ash
0      HORSE  0.948806 -1.009291 -0.903208  1.542217 -1.037554
1  ORANGUTAN  0.821407 -1.344603 -0.660619  1.040773 -1.259945
2     MONKEY  0.813445 -1.121062 -0.738247  1.263637 -1.381249
3     DONKEY  0.964731 -1.260775 -0.864394  1.152205 -0.936467
4      HIPPO  0.972694 -1.568145 -0.563583  0.149319 -1.542988

In [22]:
milk = pd.read_csv("../Datasets/milk.csv")
milk

        Animal  water  protein   fat  lactose   ash
0        HORSE   90.1      2.6   1.0      6.9  0.35
1    ORANGUTAN   88.5      1.4   3.5      6.0  0.24
2       MONKEY   88.4      2.2   2.7      6.4  0.18
3       DONKEY   90.3      1.7   1.4      6.2  0.40
4        HIPPO   90.4      0.6   4.5      4.4  0.10
5        CAMEL   87.7      3.5   3.4      4.8  0.71
6        BISON   86.9      4.8   1.7      5.7  0.90
7      BUFFALO   82.1      5.9   7.9      4.7  0.78
8   GUINEA PIG   81.9      7.4   7.2      2.7  0.85
9          CAT   81.6     10.1   6.3      4.4  0.75
10         FOX   81.6      6.6   5.9      4.9  0.93
11       LLAMA   86.5      3.9   3.2      5.6  0.80
12        MULE   90.0      2.0   1.8      5.5  0.47
13         PIG   82.8      7.1   5.1      3.7  1.10
14       ZEBRA   86.2      3.0   4.8      5.3  0.70
15       SHEEP   82.0      5.6   6.4      4.7  0.91
16         DOG   76.3      9.3   9.5      3.0  1.20
17    ELEPHANT   70.7      3.6  17.6      5.6  0.63
18      RABBIT   71.3     12.3  13.1      1.9  2.30
19         RAT   72.5      9.2  12.6      3.3  1.40
20        DEER   65.9     10.4  19.7      2.6  1.40
21    REINDEER   64.8     10.7  20.3      2.5  1.40
22       WHALE   64.8     11.1  21.2      1.6  1.70
23        SEAL   46.4      9.7  42.0      0.0  0.85
24     DOLPHIN   44.9     10.6  34.9      0.9  0.53

In [23]:
X, y = milk.drop("Animal", axis=1), milk["Animal"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=26,test_size=0.3)

In [24]:
scaler = StandardScaler().set_output(transform='pandas')
X_train_scl = scaler.fit_transform(X_train)
X_test_scl = scaler.transform(X_test)

In [26]:
import os
os.environ["LOKY_MAX_CPU_COUNT"] = "4"

In [27]:
ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scl, y_train)
    y_pred = knn.predict(X_test_scl)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

     K  Score
0    1    0.0
1    2    0.0
2    3    0.0
3    4    0.0
4    5    0.0
5    6    0.0
6    7    0.0
7    8    0.0
8    9    0.0
9   10    0.0
10  11    0.0
11  12    0.0
12  13    0.0
13  14    0.0
14  15    0.0