In [ ]:
lr
Ridge 
lasso
Pipeline
imputer

In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [91]:
df = pd.read_csv("ChemicalProcess.csv")
df

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,NaN,1.0,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,NaN,1.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,0.9,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0

In [92]:
df.describe()

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
count,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,...,171.000000,176.000000,176.000000,176.000000,175.000000,175.000000,176.000000,176.000000,176.000000,176.000000
mean,40.176534,6.411420,55.688750,67.705000,12.349261,18.598636,48.910398,100.014148,17.494773,12.850057,...,0.019573,1.013636,2.534091,6.851136,0.017714,0.023714,11.206250,0.911932,1.805114,2.138068
std,1.845666,0.713923,4.034581,4.001064,1.774661,1.844141,3.746072,0.107742,0.676954,0.415176,...,0.000874,0.445083,0.649375,1.505494,0.038289,0.053824,1.941609,0.867986,0.322006,0.406904
min,35.250000,4.580000,46.870000,56.970000,9.380000,13.240000,40.600000,100.000000,15.880000,11.440000,...,0.017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,38.752500,5.977500,52.680000,64.980000,11.245000,17.235000,46.055000,100.000000,17.060000,12.602500,...,0.019000,0.700000,2.000000,7.100000,0.000000,0.000000,11.400000,0.600000,1.800000,2.100000
50%,39.970000,6.305000,55.090000,67.220000,12.100000,18.490000,48.460000,100.000000,17.510000,12.835000,...,0.020000,1.000000,3.000000,7.200000,0.000000,0.000000,11.600000,0.800000,1.900000,2.200000
75%,41.475000,6.870000,58.737500,70.427500,13.220000,19.900000,51.345000,100.000000,17.880000,13.130000,...,0.020000,1.300000,3.000000,7.300000,0.000000,0.000000,11.700000,1.025000,1.900000,2.300000
max,46.340000,8.810000,64.750000,78.250000,23.090000,24.850000,59.380000,100.830000,19.140000,14.080000,...,0.022000,2.300000,3.000000,7.500000,0.100000,0.200000,12.100000,11.000000,2.100000,2.600000

In [93]:
df.isnull().sum()

Yield                      0
BiologicalMaterial01       0
BiologicalMaterial02       0
BiologicalMaterial03       0
BiologicalMaterial04       0
BiologicalMaterial05       0
BiologicalMaterial06       0
BiologicalMaterial07       0
BiologicalMaterial08       0
BiologicalMaterial09       0
BiologicalMaterial10       0
BiologicalMaterial11       0
BiologicalMaterial12       0
ManufacturingProcess01     1
ManufacturingProcess02     3
ManufacturingProcess03    15
ManufacturingProcess04     1
ManufacturingProcess05     1
ManufacturingProcess06     2
ManufacturingProcess07     1
ManufacturingProcess08     1
ManufacturingProcess09     0
ManufacturingProcess10     9
ManufacturingProcess11    10
ManufacturingProcess12     1
ManufacturingProcess13     0
ManufacturingProcess14     1
ManufacturingProcess15     0
ManufacturingProcess16     0
ManufacturingProcess17     0
ManufacturingProcess18     0
ManufacturingProcess19     0
ManufacturingProcess20     0
ManufacturingProcess21     0
ManufacturingProcess22     1
ManufacturingProcess23     1
ManufacturingProcess24     1
ManufacturingProcess25     5
ManufacturingProcess26     5
ManufacturingProcess27     5
ManufacturingProcess28     5
ManufacturingProcess29     5
ManufacturingProcess30     5
ManufacturingProcess31     5
ManufacturingProcess32     0
ManufacturingProcess33     5
ManufacturingProcess34     5
ManufacturingProcess35     5
ManufacturingProcess36     5
ManufacturingProcess37     0
ManufacturingProcess38     0
ManufacturingProcess39     0
ManufacturingProcess40     1
ManufacturingProcess41     1
ManufacturingProcess42     0
ManufacturingProcess43     0
ManufacturingProcess44     0
ManufacturingProcess45     0
dtype: int64

In [94]:
df.dtypes

Yield                     float64
BiologicalMaterial01      float64
BiologicalMaterial02      float64
BiologicalMaterial03      float64
BiologicalMaterial04      float64
BiologicalMaterial05      float64
BiologicalMaterial06      float64
BiologicalMaterial07      float64
BiologicalMaterial08      float64
BiologicalMaterial09      float64
BiologicalMaterial10      float64
BiologicalMaterial11      float64
BiologicalMaterial12      float64
ManufacturingProcess01    float64
ManufacturingProcess02    float64
ManufacturingProcess03    float64
ManufacturingProcess04    float64
ManufacturingProcess05    float64
ManufacturingProcess06    float64
ManufacturingProcess07    float64
ManufacturingProcess08    float64
ManufacturingProcess09    float64
ManufacturingProcess10    float64
ManufacturingProcess11    float64
ManufacturingProcess12    float64
ManufacturingProcess13    float64
ManufacturingProcess14    float64
ManufacturingProcess15      int64
ManufacturingProcess16      int64
ManufacturingProcess17    float64
ManufacturingProcess18      int64
ManufacturingProcess19      int64
ManufacturingProcess20      int64
ManufacturingProcess21    float64
ManufacturingProcess22    float64
ManufacturingProcess23    float64
ManufacturingProcess24    float64
ManufacturingProcess25    float64
ManufacturingProcess26    float64
ManufacturingProcess27    float64
ManufacturingProcess28    float64
ManufacturingProcess29    float64
ManufacturingProcess30    float64
ManufacturingProcess31    float64
ManufacturingProcess32      int64
ManufacturingProcess33    float64
ManufacturingProcess34    float64
ManufacturingProcess35    float64
ManufacturingProcess36    float64
ManufacturingProcess37    float64
ManufacturingProcess38      int64
ManufacturingProcess39    float64
ManufacturingProcess40    float64
ManufacturingProcess41    float64
ManufacturingProcess42    float64
ManufacturingProcess43    float64
ManufacturingProcess44    float64
ManufacturingProcess45    float64
dtype: object

In [95]:
X,y = df.drop("Yield",axis=1), df["Yield"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=26, test_size=0.3)

In [115]:
imputer = SimpleImputer(strategy="mean").set_output(transform='pandas')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)

In [116]:
X_trn_imp.isnull().sum()

BiologicalMaterial01      0
BiologicalMaterial02      0
BiologicalMaterial03      0
BiologicalMaterial04      0
BiologicalMaterial05      0
BiologicalMaterial06      0
BiologicalMaterial07      0
BiologicalMaterial08      0
BiologicalMaterial09      0
BiologicalMaterial10      0
BiologicalMaterial11      0
BiologicalMaterial12      0
ManufacturingProcess01    0
ManufacturingProcess02    0
ManufacturingProcess03    0
ManufacturingProcess04    0
ManufacturingProcess05    0
ManufacturingProcess06    0
ManufacturingProcess07    0
ManufacturingProcess08    0
ManufacturingProcess09    0
ManufacturingProcess10    0
ManufacturingProcess11    0
ManufacturingProcess12    0
ManufacturingProcess13    0
ManufacturingProcess14    0
ManufacturingProcess15    0
ManufacturingProcess16    0
ManufacturingProcess17    0
ManufacturingProcess18    0
ManufacturingProcess19    0
ManufacturingProcess20    0
ManufacturingProcess21    0
ManufacturingProcess22    0
ManufacturingProcess23    0
ManufacturingProcess24    0
ManufacturingProcess25    0
ManufacturingProcess26    0
ManufacturingProcess27    0
ManufacturingProcess28    0
ManufacturingProcess29    0
ManufacturingProcess30    0
ManufacturingProcess31    0
ManufacturingProcess32    0
ManufacturingProcess33    0
ManufacturingProcess34    0
ManufacturingProcess35    0
ManufacturingProcess36    0
ManufacturingProcess37    0
ManufacturingProcess38    0
ManufacturingProcess39    0
ManufacturingProcess40    0
ManufacturingProcess41    0
ManufacturingProcess42    0
ManufacturingProcess43    0
ManufacturingProcess44    0
ManufacturingProcess45    0
dtype: int64

## Linear Regression

In [117]:
lr = LinearRegression()
lr.fit(X_trn_imp,y_train)
y_pred = lr.predict(X_tst_imp)
r2_score(y_test,y_pred)

-5.540605144315917

## Ridge

In [118]:
alpha = np.linspace(0.001,10,20)
scores=[]
for i in alpha:
    ridge = Ridge(alpha=i)
    ridge.fit(X_trn_imp,y_train)
    y_pred = ridge.predict(X_tst_imp)
    scores.append([i,r2_score(y_test, y_pred),root_mean_squared_error(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','r2_score','RMSE'])        
df_scores.sort_values('r2_score')

        alpha  r2_score      RMSE
0    0.001000 -7.236853  4.852652
19  10.000000 -2.834579  3.310986
18   9.473737 -2.809446  3.300117
17   8.947474 -2.783558  3.288885
16   8.421211 -2.756935  3.277293
15   7.894947 -2.729614  3.265355
14   7.368684 -2.701656  3.253093
1    0.527263 -2.693633  3.249566
13   6.842421 -2.673154  3.240545
12   6.316158 -2.644246  3.227768
11   5.789895 -2.615135  3.214850
10   5.263632 -2.586113  3.201920
9    4.737368 -2.557606  3.189168
8    4.211105 -2.530232  3.176875
2    1.053526 -2.514421  3.169753
7    3.684842 -2.504908  3.165460
6    3.158579 -2.483017  3.155559
3    1.579789 -2.469279  3.149329
5    2.632316 -2.466741  3.148177
4    2.106053 -2.459765  3.145008

In [119]:
df_scores.nlargest(1,"r2_score")

      alpha  r2_score      RMSE
4  2.106053 -2.459765  3.145008

## Lasso

In [122]:
alpha = np.linspace(0.001,10,20)
scores=[]
for i in alpha:
    lasso = Lasso(alpha=i,max_iter=100000)
    lasso.fit(X_trn_imp,y_train)
    y_pred = lasso.predict(X_tst_imp)
    scores.append([i,r2_score(y_test, y_pred),root_mean_squared_error(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','r2_score','RMSE'])        
df_scores.sort_values('r2_score')

        alpha  r2_score      RMSE
0    0.001000 -5.976816  4.466086
2    1.053526 -1.587891  2.720016
1    0.527263 -0.646273  2.169449
3    1.579789 -0.628141  2.157469
4    2.106053 -0.130343  1.797643
5    2.632316  0.192632  1.519267
19  10.000000  0.259964  1.454538
18   9.473737  0.261814  1.452718
17   8.947474  0.274142  1.440536
16   8.421211  0.298335  1.416327
15   7.894947  0.320814  1.393455
14   7.368684  0.341600  1.371967
13   6.842421  0.360702  1.351917
12   6.316158  0.378486  1.332980
6    3.158579  0.392448  1.317924
11   5.789895  0.395083  1.315062
10   5.263632  0.411138  1.297494
9    4.737368  0.427126  1.279758
8    4.211105  0.440774  1.264423
7    3.684842  0.466590  1.234892

In [123]:
df_scores.nlargest(1,"r2_score")

      alpha  r2_score      RMSE
7  3.684842   0.46659  1.234892

## Elastic Net

In [124]:
alpha = np.linspace(0.001,10,20)
ratios = np.linspace(0.001,1,20)
scores = []
for a in alpha:
    for r in ratios:
        el = ElasticNet(alpha=a,l1_ratio=r,max_iter=100000)
        el.fit(X_trn_imp,y_train)
        y_pred = el.predict(X_tst_imp)
        scores.append([a,r,r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1','r2_score'])        
df_scores.sort_values('r2_score',ascending=False)

        alpha        l1  r2_score
31   0.527263  0.579368  0.575832
45   1.053526  0.263895  0.566910
161  4.211105  0.053579  0.563433
63   1.579789  0.158737  0.534938
30   0.527263  0.526789  0.532439
..        ...       ...       ...
15   0.001000  0.789684 -5.334210
16   0.001000  0.842263 -5.469276
17   0.001000  0.894842 -5.619055
18   0.001000  0.947421 -5.786791
19   0.001000  1.000000 -5.976816

[400 rows x 3 columns]

In [125]:
df_scores.nlargest(1,"r2_score")

       alpha        l1  r2_score
31  0.527263  0.579368  0.575832


## Using Pipeline

In [126]:
imputer = SimpleImputer(strategy="mean").set_output(transform='pandas')
lr = LinearRegression()
pipe = Pipeline([("IMP",imputer),("LR",lr)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test, y_pred)

-5.540605144315917

In [127]:
# Ridge [with pipe]

In [128]:
alpha = np.linspace(0.001,10,20)
scores=[]
for i in alpha:
    ridge = Ridge(alpha=i)
    pipe = Pipeline([("IMP",imputer),("Ridge",ridge)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([i,r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','r2_score'])        
df_scores.sort_values('r2_score')

        alpha  r2_score
0    0.001000 -7.236853
19  10.000000 -2.834579
18   9.473737 -2.809446
17   8.947474 -2.783558
16   8.421211 -2.756935
15   7.894947 -2.729614
14   7.368684 -2.701656
1    0.527263 -2.693633
13   6.842421 -2.673154
12   6.316158 -2.644246
11   5.789895 -2.615135
10   5.263632 -2.586113
9    4.737368 -2.557606
8    4.211105 -2.530232
2    1.053526 -2.514421
7    3.684842 -2.504908
6    3.158579 -2.483017
3    1.579789 -2.469279
5    2.632316 -2.466741
4    2.106053 -2.459765

In [129]:
df_scores.nlargest(1,'r2_score')

      alpha  r2_score
4  2.106053 -2.459765

In [130]:
# Lasso [With Pipe]

In [134]:
alpha = np.linspace(0.001,10,20)
scores=[]
for i in alpha:
    lasso = Lasso(alpha=i,max_iter=50000)
    pipe = Pipeline([("IMP",imputer),("lasso",lasso)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([i,r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','r2_score'])        
df_scores.sort_values('r2_score')

        alpha  r2_score
0    0.001000 -5.976816
2    1.053526 -1.587891
1    0.527263 -0.646273
3    1.579789 -0.628141
4    2.106053 -0.130343
5    2.632316  0.192632
19  10.000000  0.259964
18   9.473737  0.261814
17   8.947474  0.274142
16   8.421211  0.298335
15   7.894947  0.320814
14   7.368684  0.341600
13   6.842421  0.360702
12   6.316158  0.378486
6    3.158579  0.392448
11   5.789895  0.395083
10   5.263632  0.411138
9    4.737368  0.427126
8    4.211105  0.440774
7    3.684842  0.466590

In [135]:
df_scores.nlargest(1,'r2_score')

      alpha  r2_score
7  3.684842   0.46659

In [136]:
# Elastic net

In [137]:
alpha = np.linspace(0.001,10,20)
ratios = np.linspace(0.001,1,20)
scores = []
for a in alpha:
    for r in ratios:
        el = ElasticNet(alpha=a,l1_ratio=r,max_iter=100000)
        pipe = Pipeline([("IMP",imputer),("ElasticNet",el)])
        pipe.fit(X_train, y_train)
        y_pred = pipe.predict(X_test)
        scores.append([a,r,r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1','r2_score'])        
df_scores.sort_values('r2_score',ascending=False)

        alpha        l1  r2_score
31   0.527263  0.579368  0.575832
45   1.053526  0.263895  0.566910
161  4.211105  0.053579  0.563433
63   1.579789  0.158737  0.534938
30   0.527263  0.526789  0.532439
..        ...       ...       ...
15   0.001000  0.789684 -5.334210
16   0.001000  0.842263 -5.469276
17   0.001000  0.894842 -5.619055
18   0.001000  0.947421 -5.786791
19   0.001000  1.000000 -5.976816

[400 rows x 3 columns]

In [138]:
df_scores.nlargest(1,'r2_score')

       alpha        l1  r2_score
31  0.527263  0.579368  0.575832