In [2]:
import pandas as pd
import  numpy as np

In [6]:
people = { 'first': ['Shivansh','Rudra','Anish',np.nan,'Avani',np.nan,'Missing'],
          'last':['P','N','Missing','NA','Missing',None,np.nan],
          'email':['shiv@gmail.com','rudra@gmail.com','anish@gmail.com',None,'avani@gmail.com',None,"abc@gmail.com"],
          'age': [42,13,43,None,15,None,40]}
df = pd.DataFrame(people)
df

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA             None   NaN
4     Avani  Missing  avani@gmail.com  15.0
5       NaN     None             None   NaN
6   Missing      NaN    abc@gmail.com  40.0

In [7]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3   True  False   True   True
4  False  False  False  False
5   True   True   True   True
6  False   True  False  False

In [8]:
df.dropna()

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
4     Avani  Missing  avani@gmail.com  15.0

In [9]:
df.dropna(how="all")

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA             None   NaN
4     Avani  Missing  avani@gmail.com  15.0
6   Missing      NaN    abc@gmail.com  40.0

In [10]:
df.dropna(subset=['age'])

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
4     Avani  Missing  avani@gmail.com  15.0
6   Missing      NaN    abc@gmail.com  40.0

In [11]:
df.fillna({'email':'test@gmail.com','age':0})

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA   test@gmail.com   0.0
4     Avani  Missing  avani@gmail.com  15.0
5       NaN     None   test@gmail.com   0.0
6   Missing      NaN    abc@gmail.com  40.0

In [13]:
df.isna().all()

first    False
last     False
email    False
age      False
dtype: bool

In [14]:
df.isna().any()

first    True
last     True
email    True
age      True
dtype: bool