In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("survey_results.csv")
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [4]:
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [5]:
filt = df['ConvertedCompYearly'] > 200000
df[filt]

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
30,31,I agree,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,237974.0
121,122,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Formal documentation provided by the owner of ...,...,3-5 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,Observability tools;Continuous integration (CI...,"Information Services, IT, Software Development...",Appropriate in length,Easy,200990.0
248,249,I agree,I am a developer by profession,18-24 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Other (please specify):,NaN,...,3-5 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Neither easy nor difficult,223449.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89133,89134,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,Less than 15 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,Other,Appropriate in length,Neither easy nor difficult,500000.0
89137,89138,I agree,I am a developer by profession,55-64 years old,"Independent contractor, freelancer, or self-em...",Remote,Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Formal documentation provided by the owner of ...,...,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,60-120 minutes a day,None of these,NaN,Too short,Easy,250000.0
89139,89140,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,215000.0
89141,89142,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Oth...,Formal documentation provided by the owner of ...,...,1-2 times a week,3-5 times a week,1-2 times a week,60-120 minutes a day,15-30 minutes a day,DevOps function;Automated testing;Observabilit...,Financial Services,Appropriate in length,Easy,250000.0
89157,89158,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Formal documentation provided by the owner of ...,...,Never,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Automated testing;Observability tools;Continuo...,"Information Services, IT, Software Development...",Too long,Difficult,319711.0

In [11]:
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
2,27,United States of America,250000.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go
30,24,Australia,237974.0,NaN,Go;JavaScript;Python
121,20,United States of America,200990.0,"Information Services, IT, Software Development...",Go;HTML/CSS;JavaScript;PowerShell;Python;Rust
248,6,United Kingdom of Great Britain and Northern I...,223449.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go;HTML/CSS;JavaScript...
...,...,...,...,...,...
89133,14,United States of America,500000.0,Other,C#;JavaScript;SQL;TypeScript
89137,42,Kenya,250000.0,NaN,Bash/Shell (all shells);Go;HTML/CSS;JavaScript
89139,13,United States of America,215000.0,NaN,Bash/Shell (all shells);C++;JavaScript;Python
89141,14,United States of America,250000.0,Financial Services,C#;C++;Java;Ruby;Scala;SQL;TypeScript
89157,17,Canada,319711.0,"Information Services, IT, Software Development...",Java;Kotlin

In [12]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python',na=False)
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
7,5,United States of America,80000.0,Financial Services,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript
9,6,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript
10,14,United States of America,NaN,Other,C#;C++;HTML/CSS;JavaScript;Python
11,10,Australia,78003.0,NaN,C#;HTML/CSS;JavaScript;Kotlin;PowerShell;Pytho...
...,...,...,...,...,...
89172,38,Spain,NaN,"Information Services, IT, Software Development...",Bash/Shell (all shells);HTML/CSS;JavaScript;Pe...
89176,2,Greece,NaN,NaN,HTML/CSS;Java;JavaScript;PHP;Python;SQL;TypeSc...
89180,5,Romania,NaN,NaN,Dart;Java;Python;SQL
89181,10,Israel,NaN,NaN,Assembly;Bash/Shell (all shells);C;C#;Python;R...
89182,3,Switzerland,NaN,NaN,Bash/Shell (all shells);C#;HTML/CSS;Java;JavaS...

In [13]:
filt = df['Country'].isin(['Australia','United States of America','India'])
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
2,27,United States of America,250000.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go
3,12,United States of America,156000.0,NaN,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...
6,4,United States of America,135000.0,"Information Services, IT, Software Development...",Ada;Clojure;Elixir;Go;HTML/CSS;Java;JavaScript...
7,5,United States of America,80000.0,Financial Services,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript
...,...,...,...,...,...
89164,6,India,NaN,Financial Services,Go;HTML/CSS;Java;JavaScript;Python
89165,6,India,NaN,"Information Services, IT, Software Development...",C;C#;C++;Java;JavaScript;TypeScript
89167,6,India,15752.0,Retail and Consumer Services,Dart;HTML/CSS;JavaScript;TypeScript
89175,10,United States of America,NaN,"Information Services, IT, Software Development...",Java;Kotlin
89178,25,United States of America,NaN,Insurance,JavaScript;TypeScript

In [14]:
filt = df['Country'].isin(['Australia','United States of America','India']) & (df['ConvertedCompYearly'] > 200000)
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
2,27,United States of America,250000.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go
30,24,Australia,237974.0,NaN,Go;JavaScript;Python
121,20,United States of America,200990.0,"Information Services, IT, Software Development...",Go;HTML/CSS;JavaScript;PowerShell;Python;Rust
273,11,United States of America,240000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;PHP;SQL
...,...,...,...,...,...
89072,35,United States of America,350000.0,"Information Services, IT, Software Development...",Assembly;Bash/Shell (all shells);HTML/CSS;Java...
89123,10,Australia,330520.0,Financial Services,Bash/Shell (all shells);C++;HTML/CSS;JavaScrip...
89133,14,United States of America,500000.0,Other,C#;JavaScript;SQL;TypeScript
89139,13,United States of America,215000.0,NaN,Bash/Shell (all shells);C++;JavaScript;Python
89141,14,United States of America,250000.0,Financial Services,C#;C++;Java;Ruby;Scala;SQL;TypeScript