In [1]:
import pandas as pd

In [4]:
data = {'FullName' : ['Rucha N','Rohit K','Kedar P','Ankita G'],
        'Email' : ['rucha07@gmail.com','rohit,10@gmail.com','kedartennis@gmail.com','ankita13@gmail.com'],
        'Salary' : [100000,120000,90000,75000]}

df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [6]:
df.sort_values(by="FullName")

   FullName                  Email  Salary
3  Ankita G     ankita13@gmail.com   75000
2   Kedar P  kedartennis@gmail.com   90000
1   Rohit K     rohit,10@gmail.com  120000
0   Rucha N      rucha07@gmail.com  100000

In [7]:
df.sort_values(by="Salary")

   FullName                  Email  Salary
3  Ankita G     ankita13@gmail.com   75000
2   Kedar P  kedartennis@gmail.com   90000
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000

In [8]:
df.sort_values(by=["FullName","Salary"], ascending = [False,True])

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [9]:
df.nsmallest(2,'Salary')

   FullName                  Email  Salary
3  Ankita G     ankita13@gmail.com   75000
2   Kedar P  kedartennis@gmail.com   90000

In [10]:
df.nlargest(2,'Salary')

  FullName               Email  Salary
1  Rohit K  rohit,10@gmail.com  120000
0  Rucha N   rucha07@gmail.com  100000

In [11]:
df = pd.DataFrame({'Head Office': {'USA':'NYC','INDIA':'PUNE','UK':'LONDON','FRANCE':'PARIS'}
                   ,'Count':{'USA':100,'INDIA':500,'UK':50,'FRANCE':200}})
df

       Head Office  Count
USA            NYC    100
INDIA         PUNE    500
UK          LONDON     50
FRANCE       PARIS    200

In [14]:
df.sort_index(ascending=False)

       Head Office  Count
USA            NYC    100
UK          LONDON     50
INDIA         PUNE    500
FRANCE       PARIS    200