In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Ridge ,LinearRegression, Lasso, ElasticNet
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
from sklearn.metrics import root_mean_squared_error, r2_score

In [2]:
import os
os.chdir("E:/Vishal_Adesh/Machine Learning/Datasets")

In [5]:
job = pd.read_csv("JobSalary2.csv")
job

   S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0        NaN        88
3     4       NaN       50.0        77
4     5      63.0       41.0        89
5     6      75.0       54.0        85
6     7       NaN       51.0        96
7     8      77.0       64.0       105

In [6]:
job.mean()

S_No          4.500000
Computer     75.333333
Marketing    52.571429
Engineer     85.625000
dtype: float64

In [7]:
job.describe()

          S_No   Computer  Marketing    Engineer
count  8.00000   6.000000   7.000000    8.000000
mean   4.50000  75.333333  52.571429   85.625000
std    2.44949  10.930081   6.852181   11.537981
min    1.00000  63.000000  41.000000   70.000000
25%    2.75000  66.000000  50.500000   76.500000
50%    4.50000  76.000000  53.000000   86.500000
75%    6.25000  82.250000  54.500000   90.750000
max    8.00000  90.000000  64.000000  105.000000

In [8]:
mean_impu = dict(job.mean())
job.fillna(mean_impu)

   S_No   Computer  Marketing  Engineer
0     1  84.000000  55.000000        75
1     2  90.000000  53.000000        70
2     3  63.000000  52.571429        88
3     4  75.333333  50.000000        77
4     5  63.000000  41.000000        89
5     6  75.000000  54.000000        85
6     7  75.333333  51.000000        96
7     8  77.000000  64.000000       105

In [10]:
median_impu = dict(job.median())
job.fillna(median_impu)

   S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0       53.0        88
3     4      76.0       50.0        77
4     5      63.0       41.0        89
5     6      75.0       54.0        85
6     7      76.0       51.0        96
7     8      77.0       64.0       105

In [11]:
from sklearn.impute import SimpleImputer

In [13]:
imputer = SimpleImputer(strategy = 'mean').set_output(transform='pandas')
imputer.fit(job)
print(imputer.statistics_)
imputer.transform(job)

[ 4.5        75.33333333 52.57142857 85.625     ]

   S_No   Computer  Marketing  Engineer
0   1.0  84.000000  55.000000      75.0
1   2.0  90.000000  53.000000      70.0
2   3.0  63.000000  52.571429      88.0
3   4.0  75.333333  50.000000      77.0
4   5.0  63.000000  41.000000      89.0
5   6.0  75.000000  54.000000      85.0
6   7.0  75.333333  51.000000      96.0
7   8.0  77.000000  64.000000     105.0