# ASSIGNMENT 5

---------
### Name : Adesh Vijay Rodiye
### PRN : 8005
--------

In [66]:
import pandas as pd

### 1. Create a Series of 5 student names.

In [67]:
names = pd.Series(["Adesh","Alice","Bob","Charlie","Deve"])
names

0      Adesh
1      Alice
2        Bob
3    Charlie
4       Deve
dtype: object

### 2. Create a Series of 5 marks and display it

In [68]:
marks = pd.Series([85, 92, 78, 64, 90]) 
print(marks)

0    85
1    92
2    78
3    64
4    90
dtype: int64

### 3. Create a Series with custom index labels like A, B, C, D.

In [69]:
s_custom = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])
print(s_custom)

A    10
B    20
C    30
D    40
dtype: int64

### 4. Access the third value from a Series

In [70]:
third_val = marks.iloc[2] 
print("Third Value:", third_val)

Third Value: 78

### 5. Access a value from a Series using its custom label.

In [75]:
val_b = s_custom['B'] 
print("Value at label 'B':", val_b)

Value at label 'B': 20

### 6. Change one value in a Series

In [76]:
marks[1] = 95 
print(marks)

0    85
1    95
2    78
3    64
4    90
dtype: int64

### 7. Add 10 to every value in a numeric Series.

In [77]:
marks_plus_10 = marks + 10 
print(marks_plus_10)

0     95
1    105
2     88
3     74
4    100
dtype: int64

### 8. Find the maximum value in a Series

In [78]:
max_val = marks.max() 
print("Maximum Value:", max_val)

Maximum Value: 95

### 9. Find the minimum value in a Series.

In [79]:
min_val = marks.min() 
print("Minimum Value:", min_val)

Minimum Value: 64

### 10. Find the mean of a numeric Series

In [80]:
mean_val = marks.mean() 
print("Mean Marks:", mean_val)

Mean Marks: 82.4

### 11. Filter only values greater than 50 in a Series

In [81]:
s_nums = pd.Series([25, 60, 45, 80, 30, 95]) 
filtered = s_nums[s_nums > 50] 
print(filtered)

1    60
3    80
5    95
dtype: int64

### 12. Create a Series from a dictionary

In [82]:
marks_dict = {'Math': 88, 'Science': 92, 'English': 79} 
s_dict = pd.Series(marks_dict)
s_dict

Math       88
Science    92
English    79
dtype: int64

### 13. Check the index of a Series.

In [83]:
s_dict.index

Index(['Math', 'Science', 'English'], dtype='object')

### 14. Check the values of a Series.

In [84]:
s_dict.values

array([88, 92, 79], dtype=int64)

### 15. Convert a Series into a list

In [85]:
marks_list = marks.tolist() 
print("List:", marks_list)

List: [85, 95, 78, 64, 90]

### 16. Check which values in a Series are null.

In [86]:
s_null = pd.Series([10, None, 30, None, 50]) 
print(s_null.isnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool

### 17. Fill missing values in a Series with 0.

In [87]:
filled_s = s_null.fillna(0) 
print(filled_s)

0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64

### 18. Count how many times each value appears in a Series

In [88]:
grades = pd.Series(['A', 'B', 'A', 'C', 'B', 'A']) 
print(grades.value_counts())

A    3
B    2
C    1
Name: count, dtype: int64

### 19. Sort a Series by values.

In [89]:
sorted_vals = marks.sort_values() 
print(sorted_vals)

3    64
2    78
0    85
4    90
1    95
dtype: int64

### 20. Sort a Series by index.

In [90]:
sorted_vals = marks.sort_index() 
print(sorted_vals)

0    85
1    95
2    78
3    64
4    90
dtype: int64

### 21. Create a DataFrame of 5 students with columns Name, Age, Marks.

In [132]:
data = {'Name': ["Adesh","Alice","Bob","Charlie","Deve"], 
        'Age': [19, 21, 18, 20, 22], 
        'Marks' : [85,90,95,90,88]}
df = pd.DataFrame(data)
df

      Name  Age  Marks
0    Adesh   19     85
1    Alice   21     90
2      Bob   18     95
3  Charlie   20     90
4     Deve   22     88

### 22. Display the first 3 rows of a DataFrame.

In [133]:
df.head(3)

    Name  Age  Marks
0  Adesh   19     85
1  Alice   21     90
2    Bob   18     95

### 23. Display the last 2 rows of a DataFrame.

In [134]:
df.tail(2)

      Name  Age  Marks
3  Charlie   20     90
4     Deve   22     88

### 24. Display only one column from a DataFrame.

In [135]:
df['Name']

0      Adesh
1      Alice
2        Bob
3    Charlie
4       Deve
Name: Name, dtype: object

### 25. Display two columns from a DataFrame.

In [136]:
df[['Name','Marks']]

      Name  Marks
0    Adesh     85
1    Alice     90
2      Bob     95
3  Charlie     90
4     Deve     88

### 26. Add a new column called Passed based on Marks > 40.

In [137]:
df['Passed'] = df['Marks'] > 40 
df

      Name  Age  Marks  Passed
0    Adesh   19     85    True
1    Alice   21     90    True
2      Bob   18     95    True
3  Charlie   20     90    True
4     Deve   22     88    True

### 27. Add a new column called Bonus with fixed value 5.

In [138]:
df['Bonus'] = 5 
df

      Name  Age  Marks  Passed  Bonus
0    Adesh   19     85    True      5
1    Alice   21     90    True      5
2      Bob   18     95    True      5
3  Charlie   20     90    True      5
4     Deve   22     88    True      5

### 28. Change the values of one existing column

In [139]:
df['Age'] = df['Age'] + 1 
df[['Name', 'Age']]

      Name  Age
0    Adesh   20
1    Alice   22
2      Bob   19
3  Charlie   21
4     Deve   23

### 29. Delete one column from a DataFrame.

In [140]:
df = df.drop(columns=['Bonus']) 
df

      Name  Age  Marks  Passed
0    Adesh   20     85    True
1    Alice   22     90    True
2      Bob   19     95    True
3  Charlie   21     90    True
4     Deve   23     88    True

### 30. Rename a column in a DataFrame.

In [141]:
df = df.rename(columns={'Passed': 'Status'}) 
df

      Name  Age  Marks  Status
0    Adesh   20     85    True
1    Alice   22     90    True
2      Bob   19     95    True
3  Charlie   21     90    True
4     Deve   23     88    True

### 31. Set Name as index of the DataFrame.

In [142]:
df_indexed = df.set_index('Name') 
df_indexed

         Age  Marks  Status
Name
Adesh     20     85    True
Alice     22     90    True
Bob       19     95    True
Charlie   21     90    True
Deve      23     88    True

### 32. Reset the index back to default integers.

In [143]:
df_reset = df_indexed.reset_index() 
df_reset

      Name  Age  Marks  Status
0    Adesh   20     85    True
1    Alice   22     90    True
2      Bob   19     95    True
3  Charlie   21     90    True
4     Deve   23     88    True

### 33. Select the first row using iloc.

In [144]:
first_row = df.iloc[0] 
first_row

Name      Adesh
Age          20
Marks        85
Status     True
Name: 0, dtype: object

### 34. Select a row using loc with label index.

In [161]:
row_aarav = df_indexed.loc['Adesh'] 
row_aarav

Age         20
Marks       85
Status    True
Name: Adesh, dtype: object

### 35. Filter students with Marks greater than 60.

In [162]:
high_marks = df[df['Marks'] > 60] 
high_marks

      Name  Age  Marks  Status Department
0    Adesh   20     85    True         CS
1    Alice   22     90    True         IT
2      Bob   19     95    True         CS
3  Charlie   21     90    True         EC
4     Deve   23     88    True         CS

### 36. Filter students whose Age is less than 20.

In [163]:
young_students = df[df['Age'] < 20] 
young_students

  Name  Age  Marks  Status Department
2  Bob   19     95    True         CS

### 37. Find the average Marks of all students.

In [164]:
avg_marks = df['Marks'].mean() 
print("Average Marks:", avg_marks)

Average Marks: 89.6

### 38. Find the student with highest Marks.

In [165]:
top_student = df.loc[df['Marks'].idxmax()]
print(top_student['Name'], "with", top_student['Marks'], "marks")

Bob with 95 marks

### 39. Sort the DataFrame by Marks in ascending order.

In [166]:
sorted_marks = df.sort_values('Marks', ascending=True) 
sorted_marks

      Name  Age  Marks  Status Department
0    Adesh   20     85    True         CS
4     Deve   23     88    True         CS
1    Alice   22     90    True         IT
3  Charlie   21     90    True         EC
2      Bob   19     95    True         CS

### 40. Sort the DataFrame by Age in descending order.

In [167]:
sorted_age = df.sort_values('Age', ascending=False) 
sorted_age

      Name  Age  Marks  Status Department
4     Deve   23     88    True         CS
1    Alice   22     90    True         IT
3  Charlie   21     90    True         EC
0    Adesh   20     85    True         CS
2      Bob   19     95    True         CS

### 41. Check DataFrame shape.

In [168]:
print("DataFrame Shape:", df.shape)

DataFrame Shape: (5, 5)

### 42. Check DataFrame column names.

In [169]:
print("Columns:", df.columns.tolist())

Columns: ['Name', 'Age', 'Marks', 'Status', 'Department']

### 43. Check DataFrame data types.

In [170]:
df.dtypes

Name          object
Age            int64
Marks          int64
Status          bool
Department    object
dtype: object

### 44. Check if any values are missing in the DataFrame.

In [171]:
df.isnull().sum()

Name          0
Age           0
Marks         0
Status        0
Department    0
dtype: int64

### 45. Fill missing values in Marks with the column mean.

In [172]:
df_missing = df.copy()
df_missing.loc[1, 'Marks'] = None
df_missing['Marks'] = df_missing['Marks'].fillna(df_missing['Marks'].mean())
df_missing[['Name', 'Marks']]

      Name  Marks
0    Adesh   85.0
1    Alice   89.5
2      Bob   95.0
3  Charlie   90.0
4     Deve   88.0

### 46. Drop rows containing missing values.

In [173]:
df_null_row = df.copy()
df_null_row.loc[1, 'Marks'] = None
df_clean = df_null_row.dropna()
df_clean

      Name  Age  Marks  Status Department
0    Adesh   20   85.0    True         CS
2      Bob   19   95.0    True         CS
3  Charlie   21   90.0    True         EC
4     Deve   23   88.0    True         CS

### 47. Count unique values in a column.

In [174]:
unique_ages = df['Age'].nunique()
print("Unique Age Count:", unique_ages)

Unique Age Count: 5

### 48. Find value counts of a categorical column like Department.

In [175]:
df['Department'] = ['CS', 'IT', 'CS', 'EC', 'CS']
print(df['Department'].value_counts())

Department
CS    3
IT    1
EC    1
Name: count, dtype: int64

### 49. Create a second DataFrame and concatenate it with the first one.

In [176]:
df

      Name  Age  Marks  Status Department
0    Adesh   20     85    True         CS
1    Alice   22     90    True         IT
2      Bob   19     95    True         CS
3  Charlie   21     90    True         EC
4     Deve   23     88    True         CS

In [177]:
df1 = pd.DataFrame({
    'Name': ['Karan'], 'Age': [20], 'Marks': [81], 
    'Status': [True], 'Department': ['IT']
})
concatenated = pd.concat([df, df1], ignore_index=True)
concatenated

      Name  Age  Marks  Status Department
0    Adesh   20     85    True         CS
1    Alice   22     90    True         IT
2      Bob   19     95    True         CS
3  Charlie   21     90    True         EC
4     Deve   23     88    True         CS
5    Karan   20     81    True         IT

### 50. Create two DataFrames with a common column and merge them.

In [178]:
df

      Name  Age  Marks  Status Department
0    Adesh   20     85    True         CS
1    Alice   22     90    True         IT
2      Bob   19     95    True         CS
3  Charlie   21     90    True         EC
4     Deve   23     88    True         CS

In [182]:
df1 = pd.DataFrame({
    'Name': ['Adesh', 'Alice', 'Bob', 'Charlie', 'Deve'],
    'City': ['Mumbai', 'Pune', 'Delhi', 'Bangalore', 'Chennai'],
    'Grade': ['A', 'A+', 'O', 'A+', 'A']
})
merged_df = pd.merge(df, df1, on='Name')
merged_df

      Name  Age  Marks  Status Department       City Grade
0    Adesh   20     85    True         CS     Mumbai     A
1    Alice   22     90    True         IT       Pune    A+
2      Bob   19     95    True         CS      Delhi     O
3  Charlie   21     90    True         EC  Bangalore    A+
4     Deve   23     88    True         CS    Chennai     A