# Assignment 4 [Pandas]

-----
### Name : Adesh Vijay Rodiye
### PRN : 8005

### Name : Vishal Kumar
### PRN : 8053
-----

## Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks

a.	Display column names of the DF

b.	Show min/max and average marks

c.	Get unique values and student count for each Department

In [328]:
import pandas as pd

In [329]:
df = pd.DataFrame({"Name":['Adesh','Sarthak','Vivek','Raghav','Vishal','Yugal'],
                   "Age":[22,23,21,23,24,20],
                   "Department":["AIDS","CS","ML","AIDS","IT","CS"],
                   "%Marks":[92,98,92,95,90,93]})
df

      Name  Age Department  %Marks
0    Adesh   22       AIDS      92
1  Sarthak   23         CS      98
2    Vivek   21         ML      92
3   Raghav   23       AIDS      95
4   Vishal   24         IT      90
5    Yugal   20         CS      93

### A.  Display column names of the DF

In [330]:
df.columns

Index(['Name', 'Age', 'Department', '%Marks'], dtype='object')

### B. Show min/max and average marks

In [331]:
df["%Marks"].agg(['min','max','average'])

min        90.000000
max        98.000000
average    93.333333
Name: %Marks, dtype: float64

###  C. Get unique values and student count for each Department

In [332]:
dept = df["Department"].value_counts() # IT RETURNS SERIES OF STUDENT COUNT FOR EACH DEPARTMENT
dept

Department
AIDS    2
CS      2
ML      1
IT      1
Name: count, dtype: int64

In [333]:
# GROUP BY DEPARTMENT,.size()- Count number of students in each department and return Series, .
dept = df.groupby("Department").size().reset_index(name="Student Count")
dept

  Department  Student Count
0       AIDS              2
1         CS              2
2         IT              1
3         ML              1

## Q2. Read csv file solar.csv

a.	Display all the plants with capacity > 500 MW

b.	Display plant details for New York plant

c.	For all the plants display Average MW Per Plant and Generation (GWh)

d.	Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)

e.	List top 5 plants for their Generation

f.	Display all plant details for states – California, Nevada, Arizona and Texas

g.	Group the plants by region, find – min/max capacity plant for each group

h.	Add following information to the existing details for the plants

	North Carolina	148	669	4.5	1162	North

In [139]:
solar = pd.read_csv("solar.csv")
solar

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

### A. Display all the plants with capacity > 500 MW

In [140]:
filt = solar["Installed Capacity (MW)"]>500
solar[filt]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South

In [334]:
# Standard query: 
solar.query("`Installed Capacity (MW)` > 500") #

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

In [335]:
# using Standard Boolean Indexing:
solar[solar["Installed Capacity (MW)"] > 500]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

### B. Display plant details for New York plant

In [143]:
solar

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [144]:
solar[solar['State']=='New York']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

### C. For all the plants display Average MW Per Plant and Generation (GWh)

In [145]:
solar[['State','Average MW Per Plant','Generation (GWh)']]

         State  Average MW Per Plant  Generation (GWh)
0   California                  15.3             10826
1      Arizona                  22.5              2550
2       Nevada                  21.6               557
3      Chicago                   7.9               590
4  Connecticut                   5.9               235
5        Texas                  15.6               354
6     New York                   4.1                84
7      Florida                  12.3               453

### D. Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)

In [146]:
solar.sort_values(by=['Generation (GWh)','Installed Capacity (MW)'],ascending=[True,False])

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

### E. List top 5 plants for their Generation

In [147]:
sorted = solar.sort_values(by="Generation (GWh)",ascending=False)
sorted.head(5)

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

In [148]:
#using nlragest
 solar.nlargest(5, "Generation (GWh)")

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

### F. Display all plant details for states – California, Nevada, Arizona and Texas

In [149]:
filt = solar['State'].isin(['California', 'Nevada', 'Arizona','Texas'])
solar[filt]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

In [150]:
solar.query("State in ['California', 'Nevada', 'Arizona', 'Texas']")

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

### G. Group the plants by region, find – min/max capacity plant for each group

In [152]:
solar.groupby("Region")['Installed Capacity (MW)'].agg(["min","max"])

        min   max
Region
East     53   118
North   261   261
South   187   535
West    238  4395

In [336]:
#assign names to new column 
solar.groupby("Region").agg(
    Min_Capacity=("Installed Capacity (MW)", "min"),
    Max_Capacity=("Installed Capacity (MW)", "max"),
)

        Min_Capacity  Max_Capacity
Region
East              53           118
North            261           669
South            187           535
West             238          4395

### H. Add following information to the existing details for the plants
    North Carolina	148	669	4.5	1162	North

In [154]:
solar

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [155]:
df = [{'State':'North Carolina', 'Number of Solar Plants':148,'Installed Capacity (MW)':669,'Average MW Per Plant':4.5,'Generation (GWh)':1162,'Region':'North'}]

In [156]:
solar = pd.concat([solar,pd.DataFrame(df)],ignore_index=True)
solar

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

## Q.3 Read csv gapminder2007.csv

a.	Display data for all Asian countries

b.	Display top and bottom 15 rows

c.	Show all the rows where life expectancy is more than 50 years and less than 80 years

d.	Show data for India, America and France

e.	Show data for all countries where name starts with ‘A’

f.	Show min/max and mean GDP and Population for each continent

g.	Show population and life expectancy for all countries 

h.	Sort the data by country names (ascending) and GDP (descending)

i.	Find top 20 most populous countries

j.	Delete all rows for a specific country

k.	Change all column names to title case

l.	Change column names: pop to Population, gdpPercap to GDP_Percap

m.	Increase Life Expectancy by 2 years for all African countries

n.	Find all the rows that contain NA values

o.	Fill NA values with 0 for numeric columns

### A. Display data for all Asian countries

In [338]:
df = pd.read_csv("gapminder2007.csv")
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [339]:
df[df['continent']=="Asia"]

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan    31889923      Asia   43.828    974.580338
7               Bahrain      708573      Asia   75.635  29796.048340
8            Bangladesh   150448339      Asia   64.062   1391.253792
18             Cambodia    14131858      Asia   59.723   1713.778686
24                China  1318683096      Asia   72.961   4959.114854
55     Hong Kong, China     6980412      Asia   82.208  39724.978670
58                India  1110396331      Asia   64.698   2452.210407
59            Indonesia   223547000      Asia   70.650   3540.651564
60                 Iran    69453570      Asia   70.964  11605.714490
61                 Iraq    27499638      Asia   59.545   4471.061906
63               Israel     6426679      Asia   80.745  25523.277100
66                Japan   127467972      Asia   82.603  31656.068060
67               Jordan     6053193      Asia   72.535   4519.461171
69     Korea, Dem. Rep.    23301725      Asia   67.297   1593.065480
70          Korea, Rep.    49044790      Asia   78.623  23348.139730
71               Kuwait     2505559      Asia   77.588  47306.989780
72              Lebanon     3921278      Asia   71.993  10461.058680
78             Malaysia    24821286      Asia   74.241  12451.655800
83             Mongolia     2874127      Asia   66.803   3095.772271
87              Myanmar    47761980      Asia   62.069    944.000000
89                Nepal    28901790      Asia   63.785   1091.359778
96                 Oman     3204897      Asia   75.640  22316.192870
97             Pakistan   169270617      Asia   65.483   2605.947580
101         Philippines    91077287      Asia   71.688   3190.481016
109        Saudi Arabia    27601038      Asia   72.777  21654.831940
113           Singapore     4553009      Asia   79.972  47143.179640
119           Sri Lanka    20378239      Asia   72.396   3970.095407
124               Syria    19314747      Asia   74.143   4184.548089
125              Taiwan    23174294      Asia   78.400  28718.276840
127            Thailand    65068149      Asia   70.616   7458.396327
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906

### B. Display top and bottom 15 rows

In [340]:
df.head(15)

                   country        pop continent  lifeExp     gdpPercap
0              Afghanistan   31889923      Asia   43.828    974.580338
1                  Albania    3600523    Europe   76.423   5937.029526
2                  Algeria   33333216    Africa   72.301   6223.367465
3                   Angola   12420476    Africa   42.731   4797.231267
4                Argentina   40301927  Americas   75.320  12779.379640
5                Australia   20434176   Oceania   81.235  34435.367440
6                  Austria    8199783    Europe   79.829  36126.492700
7                  Bahrain     708573      Asia   75.635  29796.048340
8               Bangladesh  150448339      Asia   64.062   1391.253792
9                  Belgium   10392226    Europe   79.441  33692.605080
10                   Benin    8078314    Africa   56.728   1441.284873
11                 Bolivia    9119152  Americas   65.554   3822.137084
12  Bosnia and Herzegovina    4552198    Europe   74.852   7446.298803
13                Botswana    1639131    Africa   50.728  12569.851770
14                  Brazil  190010647  Americas   72.390   9065.800825

In [341]:
df.tail(15)

                 country        pop continent  lifeExp     gdpPercap
127             Thailand   65068149      Asia   70.616   7458.396327
128                 Togo    5701579    Africa   58.420    882.969944
129  Trinidad and Tobago    1056608  Americas   69.819  18008.509240
130              Tunisia   10276158    Africa   73.923   7092.923025
131               Turkey   71158647    Europe   71.777   8458.276384
132               Uganda   29170398    Africa   51.542   1056.380121
133       United Kingdom   60776238    Europe   79.425  33203.261280
134        United States  301139947  Americas   78.242  42951.653090
135              Uruguay    3447496  Americas   76.384  10611.462990
136            Venezuela   26084662  Americas   73.747  11415.805690
137              Vietnam   85262356      Asia   74.249   2441.576404
138   West Bank and Gaza    4018332      Asia   73.422   3025.349798
139          Yemen, Rep.   22211743      Asia   62.698   2280.769906
140               Zambia   11746035    Africa   42.384   1271.211593
141             Zimbabwe   12311143    Africa   43.487    469.709298

### C. Show all the rows where life expectancy is more than 50 years and less than 80 years

In [342]:
df[(df['lifeExp'] >50) & (df['lifeExp'] < 80)]

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[109 rows x 5 columns]

In [343]:
#using query
df.query("50 < lifeExp < 80")

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[109 rows x 5 columns]

In [345]:
#using between
df[df["lifeExp"].between(50, 80, inclusive="neither")]

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[109 rows x 5 columns]

### D. Show data for India, America and France

In [302]:
df[df['country'].isin(['India','United States','France'])]

           country         pop continent  lifeExp     gdpPercap
44          France    61083916    Europe   80.657  30470.016700
58           India  1110396331      Asia   64.698   2452.210407
134  United States   301139947  Americas   78.242  42951.653090

### E. Show data for all countries where name starts with ‘A’

In [303]:
df[df['country'].str.startswith('A')]

       country       pop continent  lifeExp     gdpPercap
0  Afghanistan  31889923      Asia   43.828    974.580338
1      Albania   3600523    Europe   76.423   5937.029526
2      Algeria  33333216    Africa   72.301   6223.367465
3       Angola  12420476    Africa   42.731   4797.231267
4    Argentina  40301927  Americas   75.320  12779.379640
5    Australia  20434176   Oceania   81.235  34435.367440
6      Austria   8199783    Europe   79.829  36126.492700

### F. Show min/max and mean GDP and Population for each continent

In [304]:
df.groupby("continent").agg(
    Min_GDP=("gdpPercap", "min"),
    Max_GDP=("gdpPercap", "max"),
    Mean_GDP=("gdpPercap", "mean"),
    Min_pop=("pop", "min"),
    Max_pop=("pop", "max"),
    Mean_pop=("pop", "mean"),   
)

,Min_GDP,Max_GDP,Mean_GDP,Min_pop,Max_pop,Mean_pop
continent,,,,,,
Africa,277.551859,13206.48452,3089.032605,199579,135031164,1.787576e+07
Americas,1201.637154,42951.65309,11210.433995,1056608,301139947,3.595485e+07
Asia,944.000000,47306.98978,12473.026870,708573,1318683096,1.155138e+08
Europe,5937.029526,49357.19017,25054.481636,301931,82400996,1.953662e+07
Oceania,25185.009110,34435.36744,29810.188275,4115771,20434176,1.227497e+07

### G. Show population and life expectancy for all countries

In [305]:
df[['country','pop','lifeExp']]

                country       pop  lifeExp
0           Afghanistan  31889923   43.828
1               Albania   3600523   76.423
2               Algeria  33333216   72.301
3                Angola  12420476   42.731
4             Argentina  40301927   75.320
..                  ...       ...      ...
137             Vietnam  85262356   74.249
138  West Bank and Gaza   4018332   73.422
139         Yemen, Rep.  22211743   62.698
140              Zambia  11746035   42.384
141            Zimbabwe  12311143   43.487

[142 rows x 3 columns]

In [306]:
#setting country as index
df.set_index('country')[['pop','lifeExp']]

                         pop  lifeExp
country
Afghanistan         31889923   43.828
Albania              3600523   76.423
Algeria             33333216   72.301
Angola              12420476   42.731
Argentina           40301927   75.320
...                      ...      ...
Vietnam             85262356   74.249
West Bank and Gaza   4018332   73.422
Yemen, Rep.         22211743   62.698
Zambia              11746035   42.384
Zimbabwe            12311143   43.487

[142 rows x 2 columns]

### H. Sort the data by country names (ascending) and GDP (descending)|

In [307]:
df.sort_values(by=['country','gdpPercap'],ascending=[True,False])

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

### I. Find top 20 most populous countries

In [308]:
df.nlargest(20,"pop")

              country         pop continent  lifeExp     gdpPercap
24              China  1318683096      Asia   72.961   4959.114854
58              India  1110396331      Asia   64.698   2452.210407
134     United States   301139947  Americas   78.242  42951.653090
59          Indonesia   223547000      Asia   70.650   3540.651564
14             Brazil   190010647  Americas   72.390   9065.800825
97           Pakistan   169270617      Asia   65.483   2605.947580
8          Bangladesh   150448339      Asia   64.062   1391.253792
94            Nigeria   135031164    Africa   46.859   2013.977305
66              Japan   127467972      Asia   82.603  31656.068060
82             Mexico   108700891  Americas   76.195  11977.574960
101       Philippines    91077287      Asia   71.688   3190.481016
137           Vietnam    85262356      Asia   74.249   2441.576404
47            Germany    82400996    Europe   79.406  32170.374420
38              Egypt    80264543    Africa   71.338   5581.180998
42           Ethiopia    76511887    Africa   52.947    690.805576
131            Turkey    71158647    Europe   71.777   8458.276384
60               Iran    69453570      Asia   70.964  11605.714490
127          Thailand    65068149      Asia   70.616   7458.396327
27   Congo, Dem. Rep.    64606759    Africa   46.462    277.551859
44             France    61083916    Europe   80.657  30470.016700

### J. Delete all rows for a specific country

In [309]:
df.drop(df[df['country']=='Pakistan'].index, inplace = True)

In [310]:
df['country']

0             Afghanistan
1                 Albania
2                 Algeria
3                  Angola
4               Argentina
              ...
137               Vietnam
138    West Bank and Gaza
139           Yemen, Rep.
140                Zambia
141              Zimbabwe
Name: country, Length: 141, dtype: object

In [311]:
df[df['country']=='Pakistan']

Empty DataFrame
Columns: [country, pop, continent, lifeExp, gdpPercap]
Index: []

### K. Change all column names to title case

In [312]:
df.columns

Index(['country', 'pop', 'continent', 'lifeExp', 'gdpPercap'], dtype='object')

In [313]:
df.columns = list(map(lambda x: x.title(),df.columns))
df

                Country       Pop Continent  Lifeexp     Gdppercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

### l. Change column names: pop to Population, gdpPercap to GDP_Percap

In [314]:
df.rename(columns={"Pop":"Population","Gdppercap":"GDP_Percap"},inplace= True )

In [315]:
df

                Country  Population Continent  Lifeexp    GDP_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
1               Albania     3600523    Europe   76.423   5937.029526
2               Algeria    33333216    Africa   72.301   6223.367465
3                Angola    12420476    Africa   42.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   42.384   1271.211593
141            Zimbabwe    12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

### M. Increase Life Expectancy by 2 years for all African countries

In [316]:
df.loc[df['Continent'] == 'Africa', 'Lifeexp'] += 2

In [317]:
df

                Country  Population Continent  Lifeexp    GDP_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
1               Albania     3600523    Europe   76.423   5937.029526
2               Algeria    33333216    Africa   74.301   6223.367465
3                Angola    12420476    Africa   44.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   44.384   1271.211593
141            Zimbabwe    12311143    Africa   45.487    469.709298

[141 rows x 5 columns]

### N. Find all the rows that contain NA values

In [318]:
df[df.isna().any(axis=1)]

               Country  Population Continent  Lifeexp    GDP_Percap
20              Canada    33390141  Americas      NaN  36319.235010
25            Colombia    44227550  Americas      NaN   7006.580419
36  Dominican Republic     9319622  Americas   72.235           NaN

### O. Fill NA values with 0 for numeric columns

In [319]:
df = df.fillna({"Lifeexp":0, "GDP_Percap":0})

In [320]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Population, Continent, Lifeexp, GDP_Percap]
Index: []