# Pandas - AddRemove

In [2]:
import pandas as pd

In [3]:
data = {'FullName' : ['Rucha N','Rohit K','Kedar P','Ankita G'],
        'Email' : ['rucha07@gmail.com','rohit,10@gmail.com','kedartennis@gmail.com','ankita13@gmail.com'],
        'Salary' : [100000,120000,90000,75000]}

df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [4]:
df['Bonus'] = df['Salary']*0.15
df

   FullName                  Email  Salary    Bonus
0   Rucha N      rucha07@gmail.com  100000  15000.0
1   Rohit K     rohit,10@gmail.com  120000  18000.0
2   Kedar P  kedartennis@gmail.com   90000  13500.0
3  Ankita G     ankita13@gmail.com   75000  11250.0

In [5]:
df[['FirstName','LastName']] = df['FullName'].str.split(" ", expand=True)
df

   FullName                  Email  Salary    Bonus FirstName LastName
0   Rucha N      rucha07@gmail.com  100000  15000.0     Rucha        N
1   Rohit K     rohit,10@gmail.com  120000  18000.0     Rohit        K
2   Kedar P  kedartennis@gmail.com   90000  13500.0     Kedar        P
3  Ankita G     ankita13@gmail.com   75000  11250.0    Ankita        G

In [6]:
df['Age'] = [35,40,25,20]

In [7]:
df

   FullName                  Email  Salary    Bonus  Age
0   Rucha N      rucha07@gmail.com  100000  15000.0   35
1   Rohit K     rohit,10@gmail.com  120000  18000.0   40
2   Kedar P  kedartennis@gmail.com   90000  13500.0   25
3  Ankita G     ankita13@gmail.com   75000  11250.0   20

In [6]:
df.insert(2, 'BloodGrp', ['O+','A+','A-','B+'])
df

,FullName,Email,BloodGrp,Salary,Bonus,FirstName,LastName
0,Rucha N,rucha07@gmail.com,O+,100000,15000.0,Rucha,N
1,Rohit K,"rohit,10@gmail.com",A+,120000,18000.0,Rohit,K
2,Kedar P,kedartennis@gmail.com,A-,90000,13500.0,Kedar,P
3,Ankita G,ankita13@gmail.com,B+,75000,11250.0,Ankita,G

In [9]:
df.drop(columns=['FullName','BloodGrp'],inplace=True)
df

                   Email  Salary    Bonus FirstName LastName
0      rucha07@gmail.com  100000  15000.0     Rucha        N
1     rohit,10@gmail.com  120000  18000.0     Rohit        K
2  kedartennis@gmail.com   90000  13500.0     Kedar        P
3     ankita13@gmail.com   75000  11250.0    Ankita        G

In [29]:
data = {'FullName' : ['Rucha N','Rohit K','Kedar P','Ankita G'],
        'Email' : ['rucha07@gmail.com','rohit,10@gmail.com','kedartennis@gmail.com','ankita13@gmail.com'],
        'Salary' : [100000,120000,90000,75000]}

df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

pandas.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=<no_default>, copy=<no_default>)

In [30]:
row_data = {'FullName':'Rucha N','Email':'rucha07@gmail.com','Salary':100000}
df = pd.concat([df,pd.DataFrame([row_data])],ignore_index = True)
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000
4   Rucha N      rucha07@gmail.com  100000

In [31]:
row_data = {'FullName':['Rucha N','Kedar P'],
            'Email':['rucha07@gmail.com','kedartennis@gmail.com'],
            'Salary':[100000,90000]}
df1 = pd.DataFrame(row_data)
df1

  FullName                  Email  Salary
0  Rucha N      rucha07@gmail.com  100000
1  Kedar P  kedartennis@gmail.com   90000

In [32]:
filt = df.duplicated(subset="Salary")
df[filt]

  FullName              Email  Salary
4  Rucha N  rucha07@gmail.com  100000

In [33]:
df[~filt]

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [34]:
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000
4   Rucha N      rucha07@gmail.com  100000

In [35]:
df.drop(index=[4])

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [27]:
df.drop_duplicates(keep = 'last', inplace=True)
df

   FullName                  Email  Salary
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000
4   Rucha N      rucha07@gmail.com  100000

In [28]:
df.to_csv("clean_data.csv")