In [13]:
import pandas as pd

In [14]:
data = {'FullName' : ['Rucha N','Rohit K','Kedar P','Ankita G'],
        'Email' : ['rucha07@gmail.com','rohit,10@gmail.com','kedartennis@gmail.com','ankita13@gmail.com'],
        'Salary' : [100000,120000,90000,75000]}

df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      rucha07@gmail.com  100000
1   Rohit K     rohit,10@gmail.com  120000
2   Kedar P  kedartennis@gmail.com   90000
3  Ankita G     ankita13@gmail.com   75000

In [15]:
df['Bonus'] = df['Salary']*0.15
df

   FullName                  Email  Salary    Bonus
0   Rucha N      rucha07@gmail.com  100000  15000.0
1   Rohit K     rohit,10@gmail.com  120000  18000.0
2   Kedar P  kedartennis@gmail.com   90000  13500.0
3  Ankita G     ankita13@gmail.com   75000  11250.0

In [16]:
df['Gender'] = ['F','M','M','F']
df

   FullName                  Email  Salary    Bonus Gender
0   Rucha N      rucha07@gmail.com  100000  15000.0      F
1   Rohit K     rohit,10@gmail.com  120000  18000.0      M
2   Kedar P  kedartennis@gmail.com   90000  13500.0      M
3  Ankita G     ankita13@gmail.com   75000  11250.0      F

In [17]:
df.columns = ["Full Name","Email id","Salary","Bonus","Gender"]
df

  Full Name               Email id  Salary    Bonus Gender
0   Rucha N      rucha07@gmail.com  100000  15000.0      F
1   Rohit K     rohit,10@gmail.com  120000  18000.0      M
2   Kedar P  kedartennis@gmail.com   90000  13500.0      M
3  Ankita G     ankita13@gmail.com   75000  11250.0      F

In [18]:
df.columns = [s.lower() for s in df.columns]
df

  full name               email id  salary    bonus gender
0   Rucha N      rucha07@gmail.com  100000  15000.0      F
1   Rohit K     rohit,10@gmail.com  120000  18000.0      M
2   Kedar P  kedartennis@gmail.com   90000  13500.0      M
3  Ankita G     ankita13@gmail.com   75000  11250.0      F

In [19]:
df.columns = list(map(lambda x: x.title(),df.columns))
df

  Full Name               Email Id  Salary    Bonus Gender
0   Rucha N      rucha07@gmail.com  100000  15000.0      F
1   Rohit K     rohit,10@gmail.com  120000  18000.0      M
2   Kedar P  kedartennis@gmail.com   90000  13500.0      M
3  Ankita G     ankita13@gmail.com   75000  11250.0      F

In [20]:
df.columns = list(map(lambda x:x.upper(),df.columns))
df

  FULL NAME               EMAIL ID  SALARY    BONUS GENDER
0   Rucha N      rucha07@gmail.com  100000  15000.0      F
1   Rohit K     rohit,10@gmail.com  120000  18000.0      M
2   Kedar P  kedartennis@gmail.com   90000  13500.0      M
3  Ankita G     ankita13@gmail.com   75000  11250.0      F

In [33]:
df.rename(columns={'EMAIL ID':'EMAIL'},inplace=True)
df

  FULL NAME               EMAIL  SALARY    BONUS  GENDER     TOTAL
0   Rucha N   rucha07@gmail.com  100000  15000.0  Female  115000.0
1   Rohit K  rohit,10@gmail.com  120000  18000.0    Male  138000.0
2   Kedar P    kedarT@gmail.com   90000  13500.0    Male  103500.0
3  Ankita G  ankita13@gmail.com   75000  11250.0  Female   86250.0

In [26]:
df.loc[2,'EMAIL ID'] = "kedarT@gmail.com"
df

  FULL NAME            EMAIL ID  SALARY    BONUS GENDER
0   Rucha N   rucha07@gmail.com  100000  15000.0      F
1   Rohit K  rohit,10@gmail.com  120000  18000.0      M
2   Kedar P    kedarT@gmail.com   90000  13500.0      M
3  Ankita G  ankita13@gmail.com   75000  11250.0      F

In [27]:
df.apply(len)

FULL NAME    4
EMAIL ID     4
SALARY       4
BONUS        4
GENDER       4
dtype: int64

In [28]:
df.apply(min)

FULL NAME              Ankita G
EMAIL ID     ankita13@gmail.com
SALARY                    75000
BONUS                   11250.0
GENDER                        F
dtype: object

In [30]:
df.apply(max)

FULL NAME              Rucha N
EMAIL ID     rucha07@gmail.com
SALARY                  120000
BONUS                  18000.0
GENDER                       M
dtype: object

In [31]:
df["TOTAL"]=df.apply(lambda row: row["SALARY"] + row["BONUS"],axis=1)
df

  FULL NAME            EMAIL ID  SALARY    BONUS GENDER     TOTAL
0   Rucha N   rucha07@gmail.com  100000  15000.0      F  115000.0
1   Rohit K  rohit,10@gmail.com  120000  18000.0      M  138000.0
2   Kedar P    kedarT@gmail.com   90000  13500.0      M  103500.0
3  Ankita G  ankita13@gmail.com   75000  11250.0      F   86250.0

In [32]:
df['GENDER'] = df['GENDER'].map({"M":"Male","F":"Female"})
df

  FULL NAME            EMAIL ID  SALARY    BONUS  GENDER     TOTAL
0   Rucha N   rucha07@gmail.com  100000  15000.0  Female  115000.0
1   Rohit K  rohit,10@gmail.com  120000  18000.0    Male  138000.0
2   Kedar P    kedarT@gmail.com   90000  13500.0    Male  103500.0
3  Ankita G  ankita13@gmail.com   75000  11250.0  Female   86250.0