# Multinomial Logistic Regression / Softmax

In [32]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector,make_column_transformer

In [33]:
df = pd.read_csv("Image_Segmentation.csv")
df.head()

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.0,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.0,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.0,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.0,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.0,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811

In [34]:
X, y = df.drop("Class",axis=1), df["Class"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [35]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)

0.873015873015873

In [36]:
df["Class"].unique()

array(['BRICKFACE', 'SKY', 'FOLIAGE', 'CEMENT', 'WINDOW', 'PATH', 'GRASS'],
      dtype=object)

In [37]:
# solvers = ["lbfgs","liblinear","newton-cg","newton-cholesky","sag","saga"]
solvers = ["lbfgs","newton-cg","newton-cholesky","sag","saga"]

scores = []
for s in solvers:
    lr = LogisticRegression(solver=s)
    pipe = Pipeline([("lr",lr)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

                 K     Score
1        newton-cg  0.920635
2  newton-cholesky  0.904762
0            lbfgs  0.873016
3              sag  0.857143
4             saga  0.793651

In [38]:
import warnings

warnings.filterwarnings("ignore")

In [39]:
solvers = ["lbfgs","newton-cg","newton-cholesky","sag","saga"]
scores = []
for s in solvers:
    lr = LogisticRegression(solver=s)
    pipe = Pipeline([("lr",lr)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

                 K     Score
1        newton-cg  0.920635
2  newton-cholesky  0.904762
0            lbfgs  0.873016
3              sag  0.841270
4             saga  0.793651

In [40]:
solvers = ["lbfgs","newton-cg","newton-cholesky","sag","saga"]
Cs = np.linspace(0.001,10,20)
scores = []
for s in solvers:
    for c in Cs:
        lr = LogisticRegression(solver=s,C=c)
        lr.fit(X_train,y_train)
        y_pred = lr.predict(X_test)
        scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

            K     Score
38  newton-cg  0.920635
39  newton-cg  0.920635
35  newton-cg  0.920635
33  newton-cg  0.920635
32  newton-cg  0.920635
..        ...       ...
83       saga  0.793651
82       saga  0.793651
81       saga  0.793651
80       saga  0.777778
60        sag  0.777778

[100 rows x 2 columns]

In [42]:
# solvers = ["lbfgs","newton-cg","newton-cholesky","sag","saga"]
Cs = np.linspace(0.001,10,20)
scores = []
for c in Cs:
        lr = LogisticRegression(solver="saga",l1_ratio=1,C=c)
        lr.fit(X_train,y_train)
        y_pred = lr.predict(X_test)
        scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

       K     Score
10  saga  0.793651
1   saga  0.793651
18  saga  0.793651
17  saga  0.793651
16  saga  0.793651
15  saga  0.793651
14  saga  0.793651
13  saga  0.793651
12  saga  0.793651
11  saga  0.793651
19  saga  0.793651
9   saga  0.793651
8   saga  0.793651
7   saga  0.793651
6   saga  0.793651
5   saga  0.793651
4   saga  0.793651
3   saga  0.793651
2   saga  0.793651
0   saga  0.285714